-- =====================================================================
-- Level 3 Listening story bank.
--
-- 16 briefings of about two and a half minutes, each with 10 questions.
--
-- WHAT MAKES THIS LEVEL 3, AND NOT A HARDER LEVEL 2. Every Level 1 and Level 2 story is ONE
-- situation. Every story here carries TWO migrations running at the same time for the same
-- customer -- a Message migration and a Content migration, a Mail cutover and a Shared Drive
-- move -- and the questions are written so that a candidate who followed only one of them
-- cannot answer. Several items ask which of the two an event belonged to; several ask a
-- comparison that exists in neither scenario alone. Holding two threads apart while listening
-- once is the skill this level tests.
--
-- The combinations, and the vocabulary that goes with them, are taken from the migration
-- documentation tool: Message (Slack to Teams, Slack to Chat, Teams to Chat, Chat to Teams and
-- the same-platform moves), Mail (Outlook and Gmail in all four directions) and Content (Shared
-- Drive, SPO and OneDrive in all nine). Terminology is real and current for each: channels,
-- direct messages, threads, reactions, pinned posts and message fidelity on the Message side;
-- mailboxes, shared mailboxes, aliases, labels against folders, delegates and MX cutover on the
-- Mail side; document libraries, permissions, sharing links, version history, path length and
-- native-format conversion on the Content side.
--
-- US PROJECT LANGUAGE is deliberate and consistent, because it is what these candidates hear on
-- customer calls: kickoff, statement of work, change request, dry run, UAT, go-live, cutover
-- window, blackout period, sign-off, punch list, hypercare, escalation path, service level
-- agreement, root cause analysis, run book, stakeholder, checkpoint call, staging. Each is
-- named plainly enough to be learned from context. What is NOT here is office idiom -- no
-- boiling the ocean, no kicking tires. That was tried at Level 2 and removed: it tested
-- vocabulary nobody had been taught rather than English anybody needed.
--
-- Question design, per story: item 1 is the cause of the FIRST scenario and item 2 the cause of
-- the SECOND, each with the plausible wrong hypothesis from the narrative among the options; at
-- least two items require the two scenarios to be compared or told apart; one is arithmetic
-- across both; one separates what was DEFERRED from what was RESOLVED; the last asks which
-- sentence best summarises the whole briefing, where the wrong options are true of one scenario
-- but not of both.
--
-- QUESTIONS TEST COMPREHENSION, NOT MEMORY. An early cut asked for numbers and names stated once
-- in the briefing -- how many documents, how long the vendor took, what an option cost -- which a
-- candidate answers from short-term memory rather than from having followed anything. Those were
-- replaced: every question now turns on implication, trade-off, consequence or the speakers own
-- judgement, and its answer is present in the briefing without being a sentence to recall. The one
-- arithmetic item that survives spans BOTH migrations, so it is a calculation rather than a recall.
--
-- Seeded behind a seed_state marker. Bump the key to push a revision, and delete the old rows
-- first -- a title that already exists would otherwise attach its questions to the wrong story.
--
-- Avoid apostrophes: these are single-quoted SQL literals.
-- =====================================================================

-- ---------- Stories 1 to 4 ----------
DELETE FROM listening_question WHERE story_id IN (SELECT id FROM listening_story WHERE level = 3)
  AND NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');
DELETE FROM listening_story WHERE level = 3
  AND NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

INSERT INTO listening_story (created_at, updated_at, title, script, level, difficulty)
SELECT now(), now(), v.title, v.script, 3, 'HARD'
FROM (VALUES
    ('Ardent Financial: Two Cutovers, One Weekend',
     'Ardent Financial ran two migrations across the same weekend. The first was Message: eleven hundred users moving from Slack to Teams, with four thousand channels and nine years of direct messages. The second was Content: sixty terabytes moving from Shared Drive to SPO for the same population. Programme director Yvonne Castellanos had insisted the two run together, against advice, because Ardent had negotiated a single blackout period with its regulator and a second one would not be granted for nine months. The Message side finished early. Channels, threads, reactions and pinned posts all carried across at ninety-nine point four percent fidelity, and the only real casualty was the app integrations: forty-one Slack bots had no Teams equivalent and were listed on the punch list rather than replaced. The Content side is where the weekend was lost. Throughput on the document libraries collapsed on Saturday afternoon and engineer Marcus Feld reported that SPO was throttling the tenant, recommending they wait it out. Analyst Ruth Ijeoma checked the connector logs instead and found the cause was on the Shared Drive side: a single drive holding two hundred and twenty thousand files in one flat folder was being re-enumerated on every pass. They excluded it, recovered full throughput inside the hour, and pre-staged that drive separately. What was deferred rather than solved was sharing: eighteen thousand anyone-with-the-link URLs were converted to company-only, which Ardent accepted for internal content and refused for the client-facing library, so that library still carries open links today with no owner assigned to review them. The weekend closed at four on Sunday morning, ninety minutes inside the window. The Message migration came in eleven thousand dollars under its statement of work, and the Content migration ran nineteen thousand over, because the weekend engineering that recovered the throughput was billable and Ardent approved it in writing at two in the morning.'),

    ('Brightline Health: Mail Late, Messages Early',
     'Brightline Health moved from Gmail to Outlook for two thousand four hundred mailboxes, and at the same time from Chat to Teams for the same staff. Migration manager Aditi Raghavan planned the Mail cutover for the first weekend of May and the Message cutover for the third, deliberately two weeks apart so the helpdesk would not face both at once. It was the Message migration that arrived early and the Mail one that arrived late, and neither was for the reason anyone expected. Chat to Teams finished four days ahead because Brightline had almost no group direct messages -- clinicians communicate in shared channels by policy -- and group DMs are the slowest object in that migration. Mail slipped by six days, and the cause was not volume. It was labels. Gmail labels are not folders: a message carrying five labels appears in five places, and Brightline averaged three point four labels per message across eleven million messages. The mapping to Outlook folders had been sized as though each message landed once. Engineer Tomas Bergstrom proposed dropping to a single primary label per message, which would have finished on time and lost the clinicians their filing. Aditi refused, on the grounds that a mailbox nobody can search is not a migrated mailbox, and took the six days. Two items went to the punch list. Out-of-office messages do not migrate and had to be reset by each user, which was communicated but not enforced, so several hundred were still silent in June. And nine shared mailboxes kept their delegates only after those delegates signed in once -- described in the run book, not in the user notice. Hypercare ran for two weeks after each cutover rather than one, at a cost Brightline absorbed as part of the change request.'),

    ('Cardinal Freight: The Drive That Was Not In Scope',
     'Cardinal Freight signed a statement of work covering two moves: OneDrive to SPO for four hundred users, and Slack to Chat for the same four hundred. The Content side was straightforward and the Message side was not, but the incident that defined the project belonged to neither. During the dry run, consultant Nadia Osei found a Shared Drive holding eleven terabytes of freight documentation that appeared in no scoping document, no discovery report and no line of the statement of work. It was owned by an operations team that had not been in the kickoff call. Cardinal assumed it would simply be added. Nadia explained why that was not simple: the statement of work had been priced on OneDrive personal storage, where permissions are per user, and a Shared Drive carries group-level permissions that must be mapped to SPO groups one by one. Adding it was a change request, eleven days and forty-eight thousand dollars, not a scope clarification. The Message migration ran in parallel and threw its own problem. Slack to Chat does not carry message formatting the way Slack to Teams does, and Cardinal had a decade of runbooks written as formatted Slack posts. Those arrived as plain text with the structure gone. The team had flagged this as an out-of-scope feature at kickoff, in writing, and nobody at Cardinal had read past the summary page. Both matters went to the steering committee together. The Shared Drive was approved as a change request and delivered in the second phase; the formatting loss was accepted, because re-authoring nine hundred runbooks cost more than living with them. Cardinal signed off eight days later than planned. In the post-mortem Nadia recorded one action: the out-of-scope list must be read aloud at kickoff, not attached to it.'),

    ('Delmar Logistics: The Delta That Went Backwards',
     'Delmar Logistics had two migrations in flight. Outlook to Outlook, a tenant-to-tenant move of nine hundred mailboxes following an acquisition, and SPO to SPO for the same acquisition, sixteen terabytes across two hundred site collections. Both were designed with a delta pass a week after the main copy, which is standard. On the SPO side the delta ran clean. On the Mail side it did damage. For six days after the main copy, Delmar had left the source tenant writable at their own request, so that a finance group could close the quarter where they were used to working. Forty people did exactly that. The delta faithfully carried those source mailbox changes forward, and in nineteen mailboxes it overwrote newer items that had been created in the destination. Nothing was lost -- every overwritten item was recoverable and all nineteen were restored inside four hours -- but the finance director asked the reasonable question, and the answer was uncomfortable. The request to leave the source writable had been granted by email by one engineer, and the delta had been scheduled by another, and no step in the process required those two people to meet. Engineer Priya Rensselaer drew the distinction that the team adopted: the writable source was a legitimate business decision, and the fault was that a decision and a schedule were allowed to exist without knowing about each other. Two changes followed. A writable source now blocks a delta from being scheduled until it is explicitly acknowledged, and Delmar agreed a hard read-only date in the plan itself, which they had refused twice before. The SPO side, meanwhile, finished two days early and its only punch-list item was version history: only current versions moved under the agreed plan, which the design had stated and the site owners had not expected.')
    ) AS v(title, script)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

INSERT INTO listening_question (created_at, updated_at, story_id, ordinal, question_text,
                                option_a, option_b, option_c, option_d, correct_option)
SELECT now(), now(), s.id, v.ordinal, v.q, v.a, v.b, v.c, v.d, v.correct
FROM (VALUES
    ('Ardent Financial: Two Cutovers, One Weekend', 1, 'What actually caused the Content throughput to collapse?',
     'SPO throttling the destination tenant',
     'One Shared Drive folder holding 220,000 files being re-enumerated every pass',
     'The 18,000 sharing links being converted',
     'The Message migration competing for bandwidth', 'B'),
    ('Ardent Financial: Two Cutovers, One Weekend', 2, 'What was the only real casualty on the MESSAGE side?',
     'Forty-one Slack bots with no Teams equivalent',
     'Nine years of direct messages',
     'Threads and reactions',
     'Pinned posts in private channels', 'A'),
    ('Ardent Financial: Two Cutovers, One Weekend', 3, 'Why did Yvonne insist both migrations run on the same weekend?',
     'A second regulator-approved blackout period would not be granted for nine months',
     'The statement of work required it',
     'The two teams shared the same engineers',
     'To save on weekend engineering costs', 'A'),
    ('Ardent Financial: Two Cutovers, One Weekend', 4, 'Whose judgement proved correct, and on what basis?',
     'Marcus, because throttling is the usual cause of a collapse',
     'Yvonne, because she owned the schedule',
     'Ruth, because she read the connector logs before acting',
     'The regulator, because the window held', 'C'),
    ('Ardent Financial: Two Cutovers, One Weekend', 5, 'Which issue was DEFERRED rather than resolved?',
     'The forty-one bots',
     'The flat folder on the Shared Drive',
     'The throughput collapse',
     'The open sharing links on the client-facing library', 'D'),
    ('Ardent Financial: Two Cutovers, One Weekend', 6, 'How far did Ardent accept the change to sharing links?',
     'For all content, internal and client-facing',
     'For internal content only',
     'For the client-facing library only',
     'They rejected it entirely', 'B'),
    ('Ardent Financial: Two Cutovers, One Weekend', 7, 'Taking both migrations together, what was the net effect on cost?',
     'Thirty thousand dollars over',
     'Eleven thousand dollars under',
     'Nineteen thousand dollars over',
     'Eight thousand dollars over', 'D'),
    ('Ardent Financial: Two Cutovers, One Weekend', 8, 'Which statement is true of the MESSAGE migration but NOT the Content one?',
     'It came in under its statement of work',
     'It lost time to a folder structure',
     'It required weekend engineering to recover',
     'It left an item with no owner assigned', 'A'),
    ('Ardent Financial: Two Cutovers, One Weekend', 9, 'What does the two-in-the-morning written approval most reasonably indicate?',
     'The customer was unaware of the overrun',
     'The engineering work was carried out without approval',
     'The overrun was authorised as it happened rather than argued about afterwards',
     'The statement of work had no change process', 'C'),
    ('Ardent Financial: Two Cutovers, One Weekend', 10, 'Which sentence best summarises the whole briefing?',
     'A Message migration that failed on fidelity while the Content migration succeeded',
     'Two migrations in one window, both delayed by throttling on the destination',
     'A single content migration that overran its regulator-approved window',
     'Two migrations in one window: the Message move ran clean and under budget while the Content move lost time to a folder nobody had profiled', 'D'),
    ('Brightline Health: Mail Late, Messages Early', 1, 'Why did the MAIL migration slip by six days?',
     'The volume of eleven million messages had been underestimated',
     'Out-of-office messages had to be reset first',
     'Gmail labels put one message in several places, and the mapping was sized as though each landed once',
     'The Message cutover consumed the same engineers', 'C'),
    ('Brightline Health: Mail Late, Messages Early', 2, 'Why did the MESSAGE migration finish four days early?',
     'Chat to Teams carries fewer object types than Slack to Teams',
     'Brightline had almost no group direct messages, which are the slowest object',
     'The clinicians stopped using Chat during the window',
     'It was scheduled two weeks after the Mail cutover', 'B'),
    ('Brightline Health: Mail Late, Messages Early', 3, 'Why were the two cutovers deliberately two weeks apart?',
     'The blackout period allowed only one weekend at a time',
     'So the helpdesk would not face both at once',
     'Because Mail was expected to overrun',
     'To keep the two change requests separate', 'B'),
    ('Brightline Health: Mail Late, Messages Early', 4, 'Tomas proposal would have met the date. What would it have changed for the clinicians?',
     'Their mail would have arrived without any folder structure at all',
     'They would have had to reapply every label by hand',
     'Their older mail would have been left behind in Gmail',
     'Each message would have sat in one place instead of the several places they had filed it', 'D'),
    ('Brightline Health: Mail Late, Messages Early', 5, 'What was Aditi reasoning for refusing it?',
     'The change request had not been approved',
     'The clinicians had been promised full fidelity',
     'A mailbox nobody can search is not a migrated mailbox',
     'It would have breached the service level agreement', 'C'),
    ('Brightline Health: Mail Late, Messages Early', 6, 'Why did the label structure make the mail migration slower than its message count suggested?',
     'A message filed under several labels has to be placed several times, so the work exceeds the message count',
     'Labels have to be recreated before any message can move',
     'The destination rejects messages carrying more than one label',
     'Labels are migrated last, after every folder is built', 'A'),
    ('Brightline Health: Mail Late, Messages Early', 7, 'Which punch-list item was communicated but NOT enforced?',
     'Resetting out-of-office messages',
     'The delegate sign-in for nine shared mailboxes',
     'The label mapping decision',
     'The extra week of hypercare', 'A'),
    ('Brightline Health: Mail Late, Messages Early', 8, 'What distinguishes how the two punch-list items were communicated?',
     'One was a change request and the other was not',
     'One was in the statement of work and the other was not',
     'Both were communicated identically',
     'One went to users and the other only to the run book', 'D'),
    ('Brightline Health: Mail Late, Messages Early', 9, 'What does this briefing most reasonably suggest about migration estimates?',
     'How a platform STRUCTURES its objects can matter more than how many there are',
     'Message migrations are always faster than mail migrations',
     'Volume is the least reliable predictor of duration',
     'Estimates should assume the worst case for every object type', 'A'),
    ('Brightline Health: Mail Late, Messages Early', 10, 'Which sentence best summarises the whole briefing?',
     'A message migration that finished early because it was scheduled second',
     'Two cutovers delayed by a shared helpdesk constraint',
     'Two cutovers where the fast one was fast for a structural reason and the slow one was slow for one too',
     'A mail migration that lost clinician filing to meet its date', 'C'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 1, 'What did Nadia find during the dry run?',
     'A permissions model SPO could not represent',
     'A OneDrive quota that had been exceeded',
     'Slack channels that had not been counted',
     'A Shared Drive of eleven terabytes in no scoping document', 'D'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 2, 'Why was adding it a change request rather than a clarification?',
     'The price assumed per-user permissions, and a Shared Drive needs group permissions mapped one by one',
     'The eleven terabytes exceeded the contracted volume',
     'The customer had not signed the discovery report',
     'The operations team had not attended the kickoff call', 'A'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 3, 'What went wrong on the MESSAGE side?',
     'Direct messages were not carried across',
     'Slack to Chat does not carry message formatting, so formatted runbooks arrived as plain text',
     'Channel membership had to be rebuilt by hand',
     'Reactions and pinned posts were lost', 'B'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 4, 'How had that formatting loss been handled beforehand?',
     'It was flagged in writing as out of scope at kickoff',
     'It was covered by the change request',
     'It was raised only after the dry run',
     'It had not been identified', 'A'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 5, 'What does treating the extra drive as a change request rather than a clarification reveal about the original price?',
     'It assumed the operations team would attend the kickoff call',
     'It had been priced too low across the whole engagement',
     'It excluded any content discovered after kickoff, whatever its type',
     'It had been priced on a permissions model that the new drive did not share', 'D'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 6, 'How did the steering committee decide on the two matters?',
     'Rejected the drive and re-authored the runbooks',
     'Approved both as change requests',
     'Approved the drive as a change request; accepted the formatting loss',
     'Deferred both to a second phase', 'C'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 7, 'Why was living with the formatting loss the cheaper option?',
     'The runbooks were rarely used',
     'Chat could not display formatting at all',
     'Re-authoring nine hundred runbooks cost more than accepting it',
     'The operations team preferred plain text', 'C'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 8, 'What do the two problems have in common?',
     'Both were things the customer had been told but had not taken in',
     'Both were caused by the migration tooling',
     'Both were discovered after go-live',
     'Both were resolved by change requests', 'A'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 9, 'What does Nadia post-mortem action address?',
     'The pricing model for Shared Drives',
     'How out-of-scope items are communicated, not what they are',
     'Who is invited to a dry run',
     'The formatting limits of Slack to Chat', 'B'),
    ('Cardinal Freight: The Drive That Was Not In Scope', 10, 'Which sentence best summarises the whole briefing?',
     'A message migration that lost formatting because of a tooling defect',
     'Two migrations where both surprises were failures of reading rather than of engineering',
     'Two migrations delayed by an unscoped Shared Drive',
     'A project that overran because the steering committee could not decide', 'B'),
    ('Delmar Logistics: The Delta That Went Backwards', 1, 'What caused nineteen mailboxes to lose newer items?',
     'A fault in the tenant-to-tenant migration tool',
     'A delta pass carrying forward changes from a source that was still writable',
     'Users restoring older items by mistake',
     'The SPO delta running against the wrong site collection', 'B'),
    ('Delmar Logistics: The Delta That Went Backwards', 2, 'Why was the source left writable?',
     'It had been overlooked at cutover',
     'Delmar asked for it so a finance group could close the quarter',
     'The delta pass required it',
     'The acquisition agreement demanded it', 'B'),
    ('Delmar Logistics: The Delta That Went Backwards', 3, 'What was actually lost?',
     'Nothing: every overwritten item was recoverable',
     'Six days of finance work',
     'Version history on the SPO side',
     'Nineteen mailboxes', 'A'),
    ('Delmar Logistics: The Delta That Went Backwards', 4, 'What distinction did Priya draw?',
     'Between a tool fault and a user fault',
     'Between the Mail and SPO deltas',
     'Between the writable source, which was legitimate, and a decision and a schedule not knowing about each other',
     'Between recoverable and unrecoverable items', 'C'),
    ('Delmar Logistics: The Delta That Went Backwards', 5, 'Which change addresses the process rather than the symptom?',
     'A writable source now blocks a delta from being scheduled until acknowledged',
     'Restoring the nineteen mailboxes',
     'Telling finance to work in the destination',
     'Running the SPO delta first', 'A'),
    ('Delmar Logistics: The Delta That Went Backwards', 6, 'What had Delmar refused twice before and now agreed?',
     'Paying for the restoration',
     'A delta pass at all',
     'A hard read-only date in the plan',
     'A tenant-to-tenant migration', 'C'),
    ('Delmar Logistics: The Delta That Went Backwards', 7, 'What was the only punch-list item on the SPO side?',
     'Site collection permissions',
     'Only current versions moved, which site owners had not expected',
     'Two hundred site collections were miscounted',
     'The delta pass ran late', 'B'),
    ('Delmar Logistics: The Delta That Went Backwards', 8, 'How did the two deltas differ in outcome?',
     'The SPO delta was cancelled and the Mail delta ran',
     'Both overwrote newer items',
     'The SPO delta ran clean; the Mail delta overwrote newer items',
     'The Mail delta ran clean and the SPO delta failed', 'C'),
    ('Delmar Logistics: The Delta That Went Backwards', 9, 'What does the SPO version-history item most reasonably illustrate?',
     'Site owners should approve the design',
     'The design was wrong',
     'Version history should always be migrated',
     'Something can be correctly designed, correctly delivered and still surprise the people who use it', 'D'),
    ('Delmar Logistics: The Delta That Went Backwards', 10, 'Which sentence best summarises the whole briefing?',
     'Two deltas that both overwrote newer content',
     'An SPO migration that finished early despite a delta failure',
     'A mail migration that lost nineteen mailboxes after an acquisition',
     'Two deltas from one acquisition: one uneventful, one that did damage because two correct decisions never met', 'D')
    ) AS v(story_title, ordinal, q, a, b, c, d, correct)
JOIN listening_story s ON s.level = 3 AND s.title = v.story_title
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

-- ---------- Stories 5 to 8 ----------
INSERT INTO listening_story (created_at, updated_at, title, script, level, difficulty)
SELECT now(), now(), v.title, v.script, 3, 'HARD'
FROM (VALUES
    ('Ferro Manufacturing: The Alias Nobody Owned',
     'When Ferro Manufacturing acquired a competitor, two migrations followed. Gmail to Outlook for six hundred acquired staff, and Teams to Teams, a tenant-to-tenant consolidation of both companies channels. Architect Lena Vogel sequenced them so that Mail went first, because a Teams tenant move depends on the identities the Mail move creates. The Mail side hit a problem that was neither volume nor labels. Ferro and the acquired company both used the same corporate suffix on their mail domain, and a domain can live in exactly one tenant. Removing it from the source broke mail for six hundred people for as long as the gap lasted, and Lena could not get that gap below four hours. Finance director Paolo Renzi wanted it done in one night. Lena proposed the opposite: move the six hundred users first onto a temporary routing address, let them work for two weeks, and move the domain only when almost nobody was still behind it. Paolo objected that clients would see an unfamiliar address for a fortnight. Lena answered with a measurement rather than an argument: eleven percent of outbound mail went to external clients, and ninety percent of that went to twenty-six regular contacts who could be told directly. Her plan was approved and the four-hour gap eventually affected six mailboxes instead of six hundred. The Teams side then produced its own surprise. Channel membership migrated cleanly, but forty guest accounts belonging to the acquired company suppliers did not: guest identities are issued by the destination tenant and must be re-invited, and each invitation looks like a phishing message to a supplier who was never told. Ferro sent a signed notice from its own procurement team first, then re-invited in waves. Two items were left open. Seventeen distribution lists were recreated by hand and never reconciled against the originals, and a shared mailbox called Warranty Claims retained its delegates only after each delegate signed in once -- three of them had not signed in by the closure meeting.'),

    ('Granite Partners: Consolidation on Both Sides',
     'Granite Partners is an architecture practice that merged three offices, and it ran two consolidations at once. SPO to OneDrive, moving eight hundred personal work areas out of departmental sites where they had accumulated wrongly, and Slack to Slack, folding three separate workspaces into one. Both were about cleaning up rather than moving platforms, and both were harder than a platform move for that reason. On the Content side the obstacle was path length. Files that had lived four folders deep inside a site collection went five deep in a personal area, and eleven thousand of them breached the path-length limit at the destination. Engineer Callum Reyes wanted to truncate the folder names automatically. Practice manager Ingrid Sorensen refused: the folder names are project codes and a truncated code is a lost drawing. Instead they flattened by one level, which fixed nine thousand of the eleven, and the remaining two thousand were renamed by the project teams themselves against a list. That took eleven working days of the customer own time, which nobody had planned for and which does not appear in any invoice. On the Message side, the three Slack workspaces had overlapping channel names -- each office had a general, a projects and a site-issues channel -- and Slack to Slack cannot merge two channels into one. They had to be migrated as separate channels with a suffix and then archived or merged manually afterwards. Granite chose to keep all three of each and let them die naturally, which the team advised against and recorded as accepted risk. The consolidation completed on schedule. In the post-mortem Ingrid made one observation that Callum wrote into the run book: on a same-platform consolidation, the technical work is easy and the naming decisions are the project, so the naming decisions should be taken before the kickoff call rather than during the dry run.'),

    ('Halloway Media: Going the Other Way',
     'Halloway Media moved in the direction most suppliers rarely see: Outlook to Gmail for nine hundred staff, and Teams to Chat for the same population, after a group-wide decision to standardise on Google. Migration lead Farid Haddad had run the reverse of both many times and warned the steering committee that experience does not simply reverse. On the Mail side the losses land differently. Folders map to labels without difficulty, but Outlook rules do not migrate to Gmail filters, and Halloway staff averaged nine rules each. Nine hundred people rebuilding nine rules is eight thousand small tasks that no project plan contains. Farid did not try to automate it. He had the top twenty rules across the company identified, published as a one-page recipe, and accepted that the long tail would be rebuilt by people as they missed them. On the Message side the loss was formatting and threading depth: Teams replies inside a channel post map into Chat threads unevenly, and code blocks -- which a media engineering team uses constantly -- arrive as plain text. That was declared out of scope at kickoff and read aloud, following the practice adopted after an earlier project where an out-of-scope list was attached and never read. The unexpected problem was neither of these. It was calendar. Recurring meetings with an end date migrate cleanly; recurring meetings with no end date and an exception -- one moved occurrence in a weekly series -- produced duplicates in about four percent of series. Fixing them is manual. Halloway accepted three hundred and forty duplicates as a punch-list item, cleared two hundred within hypercare, and closed the project with the rest still open and an owner named in the customer own IT team. Farid recorded that his warning to the steering committee had been correct in principle and wrong in detail: the reverse direction was harder, but not in the places he had predicted.'),

    ('Ironvale Utilities: Retention on Two Fronts',
     'Ironvale Utilities operates under a regulator that requires certain records to be held for twenty-five years, and it ran two migrations under that obligation at the same time: Shared Drive to OneDrive for eleven hundred staff, and Chat to Chat, a tenant consolidation of its two regional operating companies. Compliance officer Marta Reyes was the decisive voice on both. On the Content side the trap is well known to the team and invisible to everyone else. Retention labels travel with a document, but the RULES behind those labels are configured in the destination, and a label with no rule behind it is decorative. Two point one million documents carried labels. Migrated before the rules were rebuilt, every one of them would have arrived looking correctly classified and behaving as though it were not classified at all -- nothing on any screen would look wrong. Rebuilding the rules first added five weeks. Engineer Ben Kirchner proposed migrating the seven-year content first while the twenty-five-year rules were built in parallel, which would have recovered three of those weeks. Marta rejected it, and her reason was not technical: an inspector who found any document in an unclassified state would question the entire programme, and that conversation costs more than five weeks. On the Message side the same principle produced the opposite answer. Chat messages under legal hold cannot be migrated while the hold is active, and Ironvale had four holds covering roughly nine thousand messages. Marta did not delay the migration for them. Those conversations stayed in the source tenant, which remains licensed for two more years at eleven thousand dollars a year, and the rest moved on schedule. Asked why she blocked one migration and let the other proceed, she gave a one-line answer that went into the run book: a rule you cannot evidence is a risk, and a message you deliberately left behind is a record.')
    ) AS v(title, script)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

INSERT INTO listening_question (created_at, updated_at, story_id, ordinal, question_text,
                                option_a, option_b, option_c, option_d, correct_option)
SELECT now(), now(), s.id, v.ordinal, v.q, v.a, v.b, v.c, v.d, v.correct
FROM (VALUES
    ('Ferro Manufacturing: The Alias Nobody Owned', 1, 'What was the central obstacle on the MAIL side?',
     'Both companies used the same mail domain, and a domain lives in one tenant only',
     'Six hundred mailboxes exceeded the tenant limit',
     'Gmail labels could not map to Outlook folders',
     'The acquired company refused the routing address', 'A'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 2, 'What was the surprise on the MESSAGE side?',
     'Channel membership had to be rebuilt',
     'Forty supplier guest accounts had to be re-invited by the destination tenant',
     'Threads arrived without their replies',
     'The two tenants had overlapping channel names', 'B'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 3, 'Why did Lena sequence Mail before Teams?',
     'Mail was the larger migration',
     'The finance director asked for it',
     'A Teams tenant move depends on the identities the Mail move creates',
     'The regulator required it', 'C'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 4, 'How did Lena answer Paolo objection?',
     'She argued that clients would not notice',
     'She escalated to the steering committee',
     'She shortened the temporary period to one week',
     'She measured the outbound mail and showed how few contacts were affected', 'D'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 5, 'The four-hour gap was never shortened. Why did it end up affecting almost nobody?',
     'The gap was moved to a weekend when nobody was working',
     'The acquired company kept its own domain after all',
     'The clients had been told directly, so nothing was missed',
     'Most users had already been moved behind a temporary address before the domain went', 'D'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 6, 'Why did Ferro send a procurement notice before re-inviting guests?',
     'The invitations would otherwise look like phishing to suppliers',
     'The suppliers had to approve the acquisition',
     'Guest accounts cost extra per invitation',
     'The destination tenant required it', 'A'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 7, 'What do the unreconciled distribution lists and the unsigned-in delegates have in common as risks?',
     'Both will fail loudly the first time somebody uses them',
     'Both look complete from the migration side and only surface when a person tries to use them',
     'Both are already broken and will be reported within days',
     'Both were caused by the shared domain and clear with it', 'B'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 8, 'What did the Warranty Claims mailbox need before delegates worked?',
     'A change request',
     'Its alias to be recreated',
     'Each delegate to sign in once',
     'A separate tenant-to-tenant pass', 'C'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 9, 'What do the guest accounts and the delegates have in common?',
     'Both needed an action from a person outside the migration team before they worked',
     'Both were lost permanently',
     'Both were caused by the shared domain',
     'Both were resolved during hypercare', 'A'),
    ('Ferro Manufacturing: The Alias Nobody Owned', 10, 'Which sentence best summarises the whole briefing?',
     'Two moves delayed by a domain that could not be shared between tenants',
     'Two moves after an acquisition, where sequencing solved the domain clash and the human steps were what stayed open',
     'A mail migration that broke six hundred mailboxes for four hours',
     'A Teams consolidation blocked by supplier guest accounts', 'B'),
    ('Granite Partners: Consolidation on Both Sides', 1, 'What was the obstacle on the CONTENT side?',
     'Eight hundred personal areas exceeded the storage quota',
     'Project codes were duplicated across offices',
     'Site collections could not be read by the connector',
     'Eleven thousand files breached the path-length limit at the destination', 'D'),
    ('Granite Partners: Consolidation on Both Sides', 2, 'Why did Ingrid refuse automatic truncation?',
     'It would have taken longer than renaming',
     'The tool could not truncate safely',
     'The regulator forbade renaming',
     'The folder names are project codes, and a truncated code is a lost drawing', 'D'),
    ('Granite Partners: Consolidation on Both Sides', 3, 'What did flattening by one level achieve?',
     'It fixed nine thousand, leaving two thousand to be renamed by project teams',
     'It fixed two thousand, leaving nine thousand outstanding',
     'It fixed all eleven thousand files',
     'It removed the need for renaming entirely', 'A'),
    ('Granite Partners: Consolidation on Both Sides', 4, 'What cost does the briefing say appears in no invoice?',
     'The archived Slack channels',
     'The extra storage in the personal areas',
     'Eleven working days of the customer own renaming effort',
     'The dry run', 'C'),
    ('Granite Partners: Consolidation on Both Sides', 5, 'What was the obstacle on the MESSAGE side?',
     'Direct messages could not be consolidated',
     'Three workspaces had overlapping channel names and Slack to Slack cannot merge channels',
     'Guest members lost access',
     'Reactions were dropped between workspaces', 'B'),
    ('Granite Partners: Consolidation on Both Sides', 6, 'What did Granite decide about the duplicate channels?',
     'Merge them manually after migration',
     'Keep all three of each and let them die naturally, against advice',
     'Archive two of each before migrating',
     'Rename them by office at source', 'B'),
    ('Granite Partners: Consolidation on Both Sides', 7, 'How was that decision recorded?',
     'As accepted risk',
     'As a change request',
     'As a punch-list item',
     'It was not recorded', 'A'),
    ('Granite Partners: Consolidation on Both Sides', 8, 'What is common to both sides of this project?',
     'Both were platform changes',
     'Both were resolved by automation',
     'Both overran their schedule',
     'Both were consolidations where the naming decisions, not the technology, were the work', 'D'),
    ('Granite Partners: Consolidation on Both Sides', 9, 'What did Ingrid observation change in the run book?',
     'Path-length limits are now checked in discovery',
     'Same-platform consolidations are priced higher',
     'Naming decisions are taken before kickoff rather than during the dry run',
     'Channels are archived automatically', 'C'),
    ('Granite Partners: Consolidation on Both Sides', 10, 'Which sentence best summarises the whole briefing?',
     'A same-platform consolidation on two fronts, where the naming and the customer own effort were the real project',
     'A consolidation delayed by path-length breaches on eleven thousand files',
     'A Slack consolidation that could not merge channels and therefore failed',
     'A content migration that finished on schedule with no open items', 'A'),
    ('Halloway Media: Going the Other Way', 1, 'What does NOT migrate from Outlook to Gmail, per this briefing?',
     'Folders, which have no label equivalent',
     'Rules, which do not become Gmail filters',
     'Calendar events of any kind',
     'Shared mailboxes', 'B'),
    ('Halloway Media: Going the Other Way', 2, 'What was the unexpected problem, on which side?',
     'Code blocks arriving as plain text, on the Message side',
     'Threading depth, on the Message side',
     'Rules rebuilding, on the Mail side',
     'Calendar duplicates from open-ended recurring series, on the Mail side', 'D'),
    ('Halloway Media: Going the Other Way', 3, 'Roughly what proportion of recurring series produced duplicates?',
     'Nine percent',
     'Twenty percent',
     'Under one percent',
     'Four percent', 'D'),
    ('Halloway Media: Going the Other Way', 4, 'How did Farid handle the rules problem?',
     'He automated the conversion of all nine rules per person',
     'He excluded rules from scope after go-live',
     'He published the top twenty rules as a recipe and accepted a long tail rebuilt by people',
     'He extended hypercare until every rule was rebuilt', 'C'),
    ('Halloway Media: Going the Other Way', 5, 'How was the formatting loss communicated?',
     'Discovered during hypercare',
     'Declared out of scope at kickoff and read aloud',
     'Raised during the dry run',
     'Attached to the kickoff pack', 'B'),
    ('Halloway Media: Going the Other Way', 6, 'Why does the briefing say the practice of reading it aloud exists?',
     'The regulator requires it',
     'Because on an earlier project an out-of-scope list was attached and never read',
     'Because kickoff calls are recorded',
     'Because customers rarely attend kickoff', 'B'),
    ('Halloway Media: Going the Other Way', 7, 'The project closed with calendar duplicates still outstanding. What does that decision most reasonably indicate?',
     'The team had run out of budget and stopped work',
     'Closure was forced on the team by the customer',
     'The duplicates could not be cleared by anyone',
     'The remaining duplicates were judged a tidy-up the customer could own rather than a reason to hold closure', 'D'),
    ('Halloway Media: Going the Other Way', 8, 'What was Farid own verdict on his warning to the steering committee?',
     'Right in principle, wrong in detail',
     'It was wrong and he withdrew it',
     'Right in every particular',
     'It was never tested', 'A'),
    ('Halloway Media: Going the Other Way', 9, 'What does this briefing most reasonably suggest about reversing a familiar migration?',
     'The difficulty is real but does not land where experience predicts',
     'It should be refused unless the team has done it before',
     'It is simply the same work in the other direction',
     'It costs the same but takes longer', 'A'),
    ('Halloway Media: Going the Other Way', 10, 'Which sentence best summarises the whole briefing?',
     'A mail migration that lost every user their rules',
     'A pair of moves that failed because the team had only run them in reverse',
     'A pair of reverse-direction moves where the known losses were managed and an unpredicted calendar fault became the punch list',
     'A message migration blocked by code-block formatting', 'C'),
    ('Ironvale Utilities: Retention on Two Fronts', 1, 'What is the trap on the CONTENT side?',
     'Retention labels cannot be migrated at all',
     'OneDrive cannot hold twenty-five-year records',
     'Labels migrate but the rules behind them do not, leaving labels decorative',
     'Shared Drive permissions do not map to OneDrive', 'C'),
    ('Ironvale Utilities: Retention on Two Fronts', 2, 'Why did Marta call that the dangerous case?',
     'Nothing on any screen would look wrong; it would surface only at inspection',
     'It cannot be corrected afterwards',
     'It affects the most documents',
     'It breaches the rule immediately', 'A'),
    ('Ironvale Utilities: Retention on Two Fronts', 3, 'Ben proposal was technically sound and was still refused. What was Marta actually weighing against it?',
     'The risk of an inspector meeting one unclassified document against the time his plan would save',
     'The cost of the extra five weeks against the licence spend',
     'Whether the seven-year content mattered less than the twenty-five-year content',
     'Whether his team had the capacity to run both in parallel', 'A'),
    ('Ironvale Utilities: Retention on Two Fronts', 4, 'On what grounds did Marta reject it?',
     'The tooling could not support it',
     'An inspector finding any unclassified document would question the whole programme',
     'The seven-year content was higher risk',
     'The regulator had already scheduled an inspection', 'B'),
    ('Ironvale Utilities: Retention on Two Fronts', 5, 'What did she decide about messages under legal hold?',
     'Migrate them with the hold reapplied at the destination',
     'Delay the whole Message migration until the holds lifted',
     'Leave them in the source tenant, which stays licensed for two more years',
     'Export them to the content platform', 'C'),
    ('Ironvale Utilities: Retention on Two Fronts', 6, 'What does keeping that source tenant cost per year?',
     'Nine thousand dollars',
     'Twenty-five thousand dollars',
     'Nothing',
     'Eleven thousand dollars', 'D'),
    ('Ironvale Utilities: Retention on Two Fronts', 7, 'Why did the same principle produce opposite decisions?',
     'The regulator treats messages and documents differently',
     'An unevidenced rule is a risk, while content deliberately left behind is a record',
     'The Message migration had no deadline',
     'The Content migration was larger', 'B'),
    ('Ironvale Utilities: Retention on Two Fronts', 8, 'If the content had migrated before the rules were rebuilt, what would anyone looking at the system have seen?',
     'Documents visibly missing their labels',
     'Nothing wrong at all',
     'An error report listing every affected document',
     'Access failures for the users of that content', 'B'),
    ('Ironvale Utilities: Retention on Two Fronts', 9, 'Which decision DELAYED a migration, and which did not?',
     'The legal holds delayed Message; the rules did not delay Content',
     'Both delayed their migrations',
     'Rebuilding retention rules delayed Content; the legal holds did not delay Message',
     'Neither delayed anything', 'C'),
    ('Ironvale Utilities: Retention on Two Fronts', 10, 'Which sentence best summarises the whole briefing?',
     'A message migration blocked entirely by four legal holds',
     'A compliance officer who delayed both migrations to satisfy a regulator',
     'A content migration that arrived unclassified and failed an inspection',
     'One compliance principle applied to two migrations, delaying one by five weeks and letting the other proceed without its held records', 'D')
    ) AS v(story_title, ordinal, q, a, b, c, d, correct)
JOIN listening_story s ON s.level = 3 AND s.title = v.story_title
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

-- ---------- Stories 9 to 12 ----------
INSERT INTO listening_story (created_at, updated_at, title, script, level, difficulty)
SELECT now(), now(), v.title, v.script, 3, 'HARD'
FROM (VALUES
    ('Juniper Retail: Inside the Freeze',
     'Juniper Retail operates a change freeze from the twentieth of November to the fifth of January, and in September its programme manager Osei Danquah discovered that two migrations had been scheduled straight through it. Chat to Teams for fourteen hundred store and head-office staff, and OneDrive to OneDrive, a tenant-to-tenant move of the same peoples personal work areas following a group restructure. The freeze protects the trading period and does not move; the last exception had been granted in a year when a payment system failed. Osei brought three options to the customer. Complete both before the twentieth of November, which required starting in the first week of October and depended on an account clean-up Juniper had not begun. Split them, running Messages before the freeze and Content in January, which meant four hundred licences held for two extra months. Or compress both into six waves instead of ten, which raises the weekly user count from a hundred and forty to two hundred and thirty and, on the desks own figures, raises helpdesk load more than proportionally. IT director Fiona Marsh chose the first and made the clean-up her own commitment, delivering it in eleven days rather than the four weeks originally scheduled, by pulling two people off another project. Both migrations completed on the fourteenth of December. There was one genuine failure inside that success. User acceptance testing for the Message side was signed off by a group of eleven head-office staff, none of whom worked in a store, and stores use Chat spaces differently -- shift handovers are posted as threaded replies to a single daily message. Nobody tested that pattern, and threaded handovers arrived in Teams flattened into a single channel post. It was reported on the first Monday of the rollout by a store manager, not by the project. The fix was a re-migration of eleven spaces. Osei recorded the cost of the two borrowed people, which fell on a project outside his own reporting, on the grounds that a plan that works by moving cost into somebody else column should say so.'),

    ('Kestrel Insurance: What the Regulator Can See',
     'Kestrel Insurance ran Slack to Chat for nine hundred staff and SPO to Shared Drive for its claims archive, both under the eye of a regulator that can demand any communication or document within ten working days. Compliance lead Douglas Whyte set one requirement over both: whatever happens, an e-discovery search run after the migration must return the same result as one run before it. That requirement did more work than any technical constraint. On the Message side it meant direct messages had to migrate, which is the slowest and most sensitive part of a Slack to Chat move, and it meant timestamps had to be preserved exactly, because a search by date range that shifts by even a day is not the same search. Migrated messages arrive with a posted-as attribution and their original timestamp in the body rather than the header, which is normal and which Douglas had to explain to his own legal team twice. On the Content side it meant the claims archive kept its version history, which doubled the volume from nine terabytes to nineteen and pushed the project three weeks longer. Engineer Sofia Bianchi asked whether current versions would do. Douglas answered that a claims file without its revisions is evidence of the outcome and not of the decision, and that the regulator asks about decisions. External sharing was the item that could not be preserved. Forty loss adjusters outside the company held links into the SPO library, and a Shared Drive shares by account rather than by link. Every adjuster had to be added as a member, which needed each firm to nominate named individuals, which took five weeks and finished after go-live. Kestrel ran the two systems side by side for that period, at a licence cost of nine thousand dollars, and Douglas signed a note into the run book: preserve the search, price the sharing, and never promise both on the same date.'),

    ('Lattimer Group: Same Platform, Different Tenant',
     'Lattimer Group is a holding company that absorbed one of its own subsidiaries, and both of its migrations were same-platform tenant moves: Gmail to Gmail for seven hundred mailboxes and Shared Drive to Shared Drive for twenty-two terabytes. Migration lead Amara Sissoko opened the kickoff call by telling the customer the thing they least expected: same platform to same platform is not the easy case, and the reason is identity. In a cross-platform move, every object is translated and the team expects to map users. In a same-platform move the objects look identical, so everybody assumes the identities are too, and they are not: a user in the source tenant and the same person in the destination are different accounts with different identifiers, and every permission, every ownership record and every shared drive membership refers to the source identifier. Lattimer had two hundred and eleven people whose corporate email had changed at some point in twelve years, and whose accounts therefore matched by name but not by address. Amara insisted on a reconciled mapping file signed by the customer HR team before a single object moved, which took nine days and was the most valuable nine days of the project. Even so, fourteen accounts had no match at all: contractors who had left, whose files were owned by nobody. Those went to an orphan drive owned by an IT service account, with a review date that has passed once already. The Mail side produced the neat mirror of the same problem. Delegates and shared mailbox permissions also refer to identifiers, so a mailbox whose delegate was one of the two hundred and eleven arrived with the delegate silently missing rather than visibly broken. Amara had the team run a permission comparison after cutover rather than trusting the migration report, which found sixty-three such cases. Her closing line in the post-mortem was that on a same-platform move the migration is the easy half and the identity reconciliation is the project.'),

    ('Merrow Energy: Copy, Prove, Delete',
     'Merrow Energy sold one of its three divisions, and the sale agreement required every record belonging to that division to be delivered to the buyer and then removed from Merrow systems by a date written into the contract. Two migrations carried it out. Teams to Chat, because the buyer runs Google, moving four hundred users conversations; and SPO to SPO, a tenant-to-tenant move of ninety thousand documents. Consultant Nadia Farrell described the work as three jobs rather than two: copy, prove, delete. The copy was uneventful and took eleven days. The proving was the project. Merrow legal team wanted evidence that content had gone; the buyer wanted evidence it had arrived intact; and the two evidence sets had to reconcile, because a mismatch of even a hundred documents would delay the completion payment. Nadia produced a manifest before deletion, had the buyer confirm receipt against it, and only then ran the removal, capturing a second manifest afterwards. A mismatch appeared anyway: the buyer count was four hundred and six lower than hers. Engineer Tomas Lindqvist assumed a failed transfer and prepared to recopy. Nadia checked first. All four hundred and six were duplicate documents that the destination had merged on arrival, which is its documented behaviour and was written in the design. A recopy would have produced the same number and cost two days. On the Message side the equivalent question had no such tidy answer. Teams channel conversations moved, but one-to-one chats between a seller employee and a buyer employee belong, in a sense, to both, and no clause in the agreement addressed them. Merrow lawyers accepted a rule that Nadia proposed on the call: one-to-one chats migrate only where both participants transfer with the division. Nine hundred conversations were therefore left behind, and the completion payment was released on time.')
    ) AS v(title, script)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

INSERT INTO listening_question (created_at, updated_at, story_id, ordinal, question_text,
                                option_a, option_b, option_c, option_d, correct_option)
SELECT now(), now(), s.id, v.ordinal, v.q, v.a, v.b, v.c, v.d, v.correct
FROM (VALUES
    ('Juniper Retail: Inside the Freeze', 1, 'What did Osei discover in September?',
     'The freeze had been moved to December',
     'The account clean-up had already been done',
     'Stores used Chat differently from head office',
     'Both migrations were scheduled straight through a change freeze', 'D'),
    ('Juniper Retail: Inside the Freeze', 2, 'What was the genuine failure inside the successful delivery?',
     'The clean-up was delivered late',
     'User acceptance testing was signed off by people who did not work in a store',
     'The compression raised helpdesk load',
     'Four hundred licences were held for two extra months', 'B'),
    ('Juniper Retail: Inside the Freeze', 3, 'What broke as a result?',
     'Direct messages were not migrated',
     'Head-office channels lost their membership',
     'Personal work areas lost version history',
     'Store shift handovers, posted as threaded replies, arrived flattened', 'D'),
    ('Juniper Retail: Inside the Freeze', 4, 'A store manager reported the handover fault, not the project. What does that tell you about the testing that had been done?',
     'The testers did not use the system the way the affected users do',
     'The testers had signed off without looking',
     'The testing was too small to be meaningful',
     'The fault appeared only after the rollout began', 'A'),
    ('Juniper Retail: Inside the Freeze', 5, 'Why was splitting the two migrations across the freeze the most expensive option, even though it required no extra work?',
     'It kept licences alive on both sides for two months of doing nothing',
     'It would have doubled the helpdesk load in January',
     'It needed a freeze exception the customer could not obtain',
     'It pushed the content migration past the audit date', 'A'),
    ('Juniper Retail: Inside the Freeze', 6, 'How did Fiona make the chosen option possible?',
     'By granting a freeze exception',
     'By delaying the Content migration to January',
     'By delivering the clean-up in eleven days, pulling two people off another project',
     'By compressing the waves', 'C'),
    ('Juniper Retail: Inside the Freeze', 7, 'What was the fix for the handover problem?',
     'Training for store managers',
     'A re-migration of eleven spaces',
     'A change request for the next phase',
     'Nothing; it was accepted', 'B'),
    ('Juniper Retail: Inside the Freeze', 8, 'Why did Osei record the cost of the two borrowed people?',
     'Because a plan that works by moving cost into another column should say so',
     'It explained the December finish date',
     'The customer asked him to',
     'It appeared in his own budget', 'A'),
    ('Juniper Retail: Inside the Freeze', 9, 'What does the UAT failure most reasonably illustrate?',
     'Testing should be done by the project team',
     'A sign-off is only as good as whether the testers use the system the way the users do',
     'Store staff should not be migrated first',
     'Threaded replies should be avoided', 'B'),
    ('Juniper Retail: Inside the Freeze', 10, 'Which sentence best summarises the whole briefing?',
     'Two migrations delayed into January by a change freeze',
     'A message migration that flattened every handover in the company',
     'Two migrations squeezed in before a freeze and delivered, with the one real fault hidden inside an unrepresentative sign-off',
     'A programme that failed because the clean-up took eleven days', 'C'),
    ('Kestrel Insurance: What the Regulator Can See', 1, 'What single requirement governed both migrations?',
     'No content could leave the country',
     'External sharing had to be preserved exactly',
     'An e-discovery search after the move must return the same result as one before it',
     'Both migrations had to finish on the same date', 'C'),
    ('Kestrel Insurance: What the Regulator Can See', 2, 'What did that requirement force on the MESSAGE side?',
     'Guest accounts had to be re-invited',
     'Direct messages had to migrate and timestamps had to be preserved exactly',
     'Reactions had to be preserved',
     'Channels had to be renamed to match the archive', 'B'),
    ('Kestrel Insurance: What the Regulator Can See', 3, 'Keeping version history doubled the volume. Why did Douglas treat that as unavoidable rather than as a cost to be argued down?',
     'The regulator had specified version history in writing',
     'Because the questions a regulator asks are about decisions, and only the revisions evidence those',
     'Because the destination could not accept documents without their history',
     'Because the claims team refused to sign off otherwise', 'B'),
    ('Kestrel Insurance: What the Regulator Can See', 4, 'How did Douglas answer Sofia question about current versions?',
     'That the regulator only asks about outcomes',
     'That a claims file without its revisions evidences the outcome but not the decision',
     'That volume was not a concern',
     'That the buyer required it', 'B'),
    ('Kestrel Insurance: What the Regulator Can See', 5, 'Which requirement could NOT be preserved?',
     'External sharing, because a Shared Drive shares by account rather than by link',
     'Timestamps on migrated messages',
     'Version history on the claims archive',
     'Direct messages', 'A'),
    ('Kestrel Insurance: What the Regulator Can See', 6, 'Adding the adjusters by account could not be done before go-live. What did that force on the project?',
     'The e-discovery requirement had to be relaxed for external users',
     'Both systems had to run side by side until the last firm had nominated its people',
     'The claims archive had to migrate without its version history',
     'The regulator had to be told that access would lapse', 'B'),
    ('Kestrel Insurance: What the Regulator Can See', 7, 'The two systems ran side by side for five weeks. What was actually being bought with that overlap?',
     'A safety net in case the e-discovery search failed',
     'Time for the version history to finish copying',
     'Time for the adjusters to be added by account so their access never lapsed',
     'Time for the legal team to understand the attribution change', 'C'),
    ('Kestrel Insurance: What the Regulator Can See', 8, 'What did Douglas have to explain to his own legal team twice?',
     'Why direct messages were in scope',
     'Why the adjusters lost their links',
     'Why version history doubled the volume',
     'That migrated messages carry a posted-as attribution with the original timestamp in the body', 'D'),
    ('Kestrel Insurance: What the Regulator Can See', 9, 'What is the practical meaning of his run-book note?',
     'Search fidelity and sharing continuity compete, so they should not share a deadline',
     'Sharing should always be dropped from scope',
     'E-discovery searches should be run only before a migration',
     'Regulated migrations should keep only current versions', 'A'),
    ('Kestrel Insurance: What the Regulator Can See', 10, 'Which sentence best summarises the whole briefing?',
     'One compliance requirement shaping two migrations, preserved on both at the price of three weeks and five weeks of overlap',
     'Two migrations that failed a regulator inspection',
     'A content migration that dropped version history to save volume',
     'A message migration blocked by direct-message sensitivity', 'A'),
    ('Lattimer Group: Same Platform, Different Tenant', 1, 'Why did Amara say same-platform moves are not the easy case?',
     'The objects look identical, so everybody assumes the identities are too, and they are not',
     'The volumes are usually larger',
     'The tooling has fewer features',
     'Same-platform moves cannot preserve permissions', 'A'),
    ('Lattimer Group: Same Platform, Different Tenant', 2, 'Why were the people whose email address had changed over the years the dangerous group, rather than simply an awkward one?',
     'They were the largest group in the mapping file',
     'Their old addresses had already been reassigned to other staff',
     'They matched by name, so a mapping could look correct while pointing at the wrong account',
     'They had the most shared drives between them', 'C'),
    ('Lattimer Group: Same Platform, Different Tenant', 3, 'What did Amara insist on before any object moved?',
     'A signed statement of work',
     'A reconciled mapping file signed by the customer HR team',
     'A dry run of the Mail side',
     'A permission comparison', 'B'),
    ('Lattimer Group: Same Platform, Different Tenant', 4, 'What happened to the fourteen accounts with no match?',
     'Their files went to an orphan drive owned by an IT service account, with a review date now passed',
     'They were merged with the nearest name match',
     'They were excluded from the migration',
     'They were deleted with the customer agreement', 'A'),
    ('Lattimer Group: Same Platform, Different Tenant', 5, 'How did the identity problem show itself on the MAIL side?',
     'Mailboxes failed to migrate entirely',
     'Delegates arrived silently missing rather than visibly broken',
     'Labels were mapped to the wrong folders',
     'Aliases were duplicated across tenants', 'B'),
    ('Lattimer Group: Same Platform, Different Tenant', 6, 'The permission comparison was run instead of trusting the migration report. What kind of fault was it looking for?',
     'Permissions that had been applied to the wrong people',
     'Permissions that took longer than expected to apply',
     'Permissions that were absent without anything having reported an error',
     'Permissions that the destination platform does not support', 'C'),
    ('Lattimer Group: Same Platform, Different Tenant', 7, 'Why did the team run that comparison at all?',
     'The regulator required it',
     'It was contractually required',
     'The customer refused to sign off without it',
     'Because they did not trust the migration report to show a silent absence', 'D'),
    ('Lattimer Group: Same Platform, Different Tenant', 8, 'What do the orphan drive and the missing delegates have in common?',
     'Both were the customer responsibility',
     'Both were caused by identity records that could not be reconciled',
     'Both were resolved before go-live',
     'Both were caused by volume', 'B'),
    ('Lattimer Group: Same Platform, Different Tenant', 9, 'Amara called the reconciliation the most valuable part of the project. What does that judgement rest on?',
     'It was the only part the customer paid separately for',
     'It took the least time of any phase',
     'It was the step that decided whether everything copied afterwards would land on the right accounts',
     'It was the only work her own team could control', 'C'),
    ('Lattimer Group: Same Platform, Different Tenant', 10, 'Which sentence best summarises the whole briefing?',
     'A mail migration that lost sixty-three mailboxes',
     'Two same-platform moves that failed because permissions cannot be migrated',
     'A content migration delayed nine days by an HR sign-off',
     'Two same-platform moves where the objects were trivial and the identity reconciliation was the entire project', 'D'),
    ('Merrow Energy: Copy, Prove, Delete', 1, 'Why did Nadia describe the work as three jobs?',
     'Because three platforms were involved',
     'Because two migrations plus a deletion had to reconcile as evidence',
     'Because the buyer ran a third system',
     'Because the contract named three deliverables', 'B'),
    ('Merrow Energy: Copy, Prove, Delete', 2, 'What did the four hundred and six document difference turn out to be?',
     'A failed transfer',
     'A counting error in the buyer manifest',
     'Documents held by a legal hold',
     'Duplicates merged by the destination, as documented in the design', 'D'),
    ('Merrow Energy: Copy, Prove, Delete', 3, 'What would Tomas planned recopy have achieved?',
     'Breached the sale agreement',
     'Recovered the missing documents',
     'Produced the same number and cost two days',
     'Satisfied the buyer lawyers', 'C'),
    ('Merrow Energy: Copy, Prove, Delete', 4, 'What was the correct order of Nadia evidence process?',
     'Buyer confirmation, deletion, manifest',
     'Deletion, manifest, buyer confirmation',
     'Manifest, buyer confirmation, deletion, second manifest',
     'Two manifests taken simultaneously', 'C'),
    ('Merrow Energy: Copy, Prove, Delete', 5, 'What question did the MESSAGE side raise that the contract did not answer?',
     'Whether channel conversations belonged to the buyer',
     'Whether Chat could receive Teams threads',
     'Who owns a one-to-one chat between a seller employee and a buyer employee',
     'Whether reactions were records', 'C'),
    ('Merrow Energy: Copy, Prove, Delete', 6, 'What rule was agreed, and by whom was it proposed?',
     'One-to-one chats migrate only where both participants transfer; proposed by Nadia on the call',
     'All one-to-one chats migrate; proposed by the buyer lawyers',
     'No one-to-one chats migrate; proposed by Merrow lawyers',
     'The decision was deferred to arbitration', 'A'),
    ('Merrow Energy: Copy, Prove, Delete', 7, 'What was the practical effect of the rule agreed for one-to-one chats?',
     'Every conversation moved, with the buyer accepting joint ownership',
     'The decision was deferred until after completion',
     'Conversations were split so each side kept its own half',
     'A block of conversations stayed with the seller rather than transferring with the division', 'D'),
    ('Merrow Energy: Copy, Prove, Delete', 8, 'What was at stake in a mismatch of even a hundred documents?',
     'A delay to the completion payment',
     'A breach of the legal hold',
     'The loss of the buyer confidence',
     'An extra eleven days of copying', 'A'),
    ('Merrow Energy: Copy, Prove, Delete', 9, 'What does the contrast between the two sides most reasonably show?',
     'Documents had a documented rule to fall back on; conversations needed one invented on the call',
     'Lawyers should draft migration plans',
     'Content is harder to migrate than messages',
     'One-to-one chats should never be migrated', 'A'),
    ('Merrow Energy: Copy, Prove, Delete', 10, 'Which sentence best summarises the whole briefing?',
     'A message migration blocked by a contract clause',
     'A divestiture where proving the move was harder than making it, and where ownership of a conversation had to be decided from scratch',
     'A divestiture in which the buyer and seller could not agree a manifest',
     'A divestiture delayed by four hundred and six missing documents', 'B')
    ) AS v(story_title, ordinal, q, a, b, c, d, correct)
JOIN listening_story s ON s.level = 3 AND s.title = v.story_title
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

-- ---------- Stories 13 to 16 ----------
INSERT INTO listening_story (created_at, updated_at, title, script, level, difficulty)
SELECT now(), now(), v.title, v.script, 3, 'HARD'
FROM (VALUES
    ('Northgate Bank: The Account That Could Not Sign In',
     'Northgate Bank ran Outlook to Outlook for eighteen hundred mailboxes and Slack to Teams for the same staff, both inside a security regime that had to approve every step. Migration manager Priyanka Menon had cleared a forty-question review before either began. The incident arrived anyway, and it arrived twice in the same shape. On the Mail side, the migration service account was blocked overnight by a conditional access policy that requires multi-factor authentication from any unrecognised location, and the migration servers were an unrecognised location. Eleven hours were lost. The exemption took forty minutes to arrange and two days to approve, because the person who could approve it was on leave and the escalation path named a role rather than a deputy. Nine days later the Slack to Teams job stopped for the same reason, on a different account, because the exemption had been raised for one account rather than for the class of accounts the migration used. Priyanka did not treat the second as a repeat of the first. In the review she separated them: the first was a gap in discovery, since nobody had asked what conditional access policies applied to service accounts, and the second was a gap in remediation, since the fix had been scoped to the symptom rather than the cause. Two changes followed. Discovery now asks for conditional access policies by name, and any exemption is raised for the account class. The Message side carried a second issue that had nothing to do with security. Slack to Teams moves private channels only where the migration account is a member, and Northgate had four hundred private channels whose owners had to add that account one at a time. Two hundred and ninety did so within the week. The remaining hundred and ten were chased for a fortnight, thirty were never actioned, and those channels stayed in Slack under a read-only licence that the bank now renews annually.'),

    ('Orlow Pharma: Where the Reports Go',
     'Orlow Pharma is headquartered in Germany, and its works council required written confirmation that no employee content would leave the European region during either of its migrations: Gmail to Outlook for twelve hundred mailboxes, and OneDrive to SPO for the same users. Architect Julien Moreau confirmed both content paths were European and then checked one component further and found the exception. Migration progress reports were generated by a service hosted in North America, and those reports contain file names, folder paths and mailbox display names -- nothing that could be called content, and everything a works council would reasonably call personal data. He raised it himself, in the same meeting where he confirmed the content path, before anyone had asked. Two options went to the council. Move the reporting to a European instance, which existed but had never been used at that scale and needed three weeks of validation; or generate reports without names, which was immediate and made troubleshooting considerably harder for his own team. The council chose the first and Orlow accepted the three weeks. Validation found a defect: a character encoding fault that mangled German file names in the European reporting instance, which the vendor fixed eight months later and which the team worked around for the duration. The migrations themselves were unremarkable except for one asymmetry worth noting. On the Mail side, a mailbox is a single object with one owner, so residency is simple. On the Content side, a document in a shared library has an owner, an editor list and a link that may have been sent anywhere, and the works council question about where content lives is genuinely harder to answer for the second than the first. Julien recommendation, accepted in principle and still not implemented, was that the standard architecture diagram show data paths rather than only content paths, because the report about the migration turned out to be the part that left the region.'),

    ('Pinehurst Council: Public by Default',
     'Pinehurst Council migrated Teams to Teams between two authorities that had merged, and Shared Drive to SPO for the same combined workforce of two thousand. Both migrations sat under freedom-of-information obligations: any resident may request a document or a recorded communication, and the authority must find it. Programme lead Elena Duarte ran the two on one plan and one risk register, which she later described as the single decision that made the project possible. The Content side raised the harder question. The two authorities had used Shared Drives with opposite conventions -- one filed by service area and one by year -- and merging them into SPO meant choosing. Elena refused to let the migration team choose. She had the records manager produce a target structure, signed, before the first wave, and the migration mapped into it. That took six weeks that the plan had not contained, and it is the reason a resident request can now be answered in one search rather than two. The Message side had a subtler problem. Teams to Teams preserves channel conversations, but the two authorities had different retention settings, one deleting chat after eighteen months and the other keeping everything. Merging tenants means one setting wins. Keeping everything is safer for freedom of information and more expensive; deleting after eighteen months is cheaper and creates a gap a requester can notice. The council chose to keep everything, and to backfill the deleted period from the archive of the authority that had it, which was possible for eleven of the eighteen months. Elena wrote the seven-month gap into the register as a known limitation with a published explanation, rather than leaving it to be discovered. In the closure meeting she noted that both decisions -- the filing structure and the retention setting -- had been taken by people whose job is records rather than technology, and that this was the point.'),

    ('Quarry Analytics: The Cost of Keeping Both',
     'Quarry Analytics had grown from forty people to four hundred through two acquisitions, and it was paying for it. Slack to Slack consolidated three workspaces into one, and SPO to OneDrive moved eleven hundred personal work areas out of a departmental site structure that had become a filing cabinet. Finance director Marianne Foss had a target rather than a deadline: reduce annual platform spend by a hundred and forty thousand dollars. That framing changed how the project was run. Every technical decision was priced. Keeping the two source Slack workspaces alive for thirty days after cutover, which the team recommends, cost eleven thousand dollars a month, so Marianne asked what the thirty days actually buys. Migration lead Ade Bakare answered honestly: across eleven previous projects, the average interval between cutover and the last genuine recovery request was nineteen days, but about two thirds of those requests could have been served from the destination by someone who simply could not find the content. That answer weakened his own recommendation and he gave it anyway. Marianne then proposed something better than either position: decommission at ten days, and before that, export the twelve highest-risk channels and the eight largest personal areas to cold storage for three months at nine hundred dollars. Ade agreed and added one condition of his own, that the export be verified by restoring three items at random before anything was switched off. The verification found one export that had completed incompletely, which was re-run. In the ten weeks that followed there were four recovery requests. Three were served from the destination, where the content had been all along. The fourth came from the cold export and concerned a channel that had not been in the original twelve; it had been added because the engineer running the export rounded up to fourteen on his own initiative. The programme came in at a hundred and fifty-two thousand dollars of annual saving, and Ade recorded the fourteenth channel specifically, because the process would not have covered it and a person did.')
    ) AS v(title, script)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

INSERT INTO listening_question (created_at, updated_at, story_id, ordinal, question_text,
                                option_a, option_b, option_c, option_d, correct_option)
SELECT now(), now(), s.id, v.ordinal, v.q, v.a, v.b, v.c, v.d, v.correct
FROM (VALUES
    ('Northgate Bank: The Account That Could Not Sign In', 1, 'What blocked the MAIL migration overnight?',
     'A private channel the account could not read',
     'A conditional access policy demanding multi-factor authentication from an unrecognised location',
     'The forty-question security review',
     'An expired service account password', 'B'),
    ('Northgate Bank: The Account That Could Not Sign In', 2, 'Why did the same thing happen again nine days later?',
     'The exemption had been raised for one account rather than the class of accounts',
     'The approver was on leave again',
     'A different policy applied to Teams',
     'The policy had been reinstated', 'A'),
    ('Northgate Bank: The Account That Could Not Sign In', 3, 'How did Priyanka classify the two incidents?',
     'The first a discovery gap, the second a remediation gap',
     'Both as discovery gaps',
     'Both as remediation gaps',
     'The first a remediation gap, the second a discovery gap', 'A'),
    ('Northgate Bank: The Account That Could Not Sign In', 4, 'Why did the exemption take two days to approve after forty minutes to arrange?',
     'The approver was on leave and the escalation path named a role rather than a deputy',
     'The bank policy imposed a waiting period',
     'It required a change request',
     'The security team disputed it', 'A'),
    ('Northgate Bank: The Account That Could Not Sign In', 5, 'What limits which private channels Slack to Teams can move?',
     'Whether the channel is archived',
     'The channel size',
     'Whether the channel has guests',
     'Whether the migration account is a member', 'D'),
    ('Northgate Bank: The Account That Could Not Sign In', 6, 'Most private channel owners acted within a week and a minority never did. What does that split suggest about how the request was made?',
     'The deadline given was too short for anyone to meet',
     'The owners had not been told what the request was for',
     'Relying on individual owners works for the willing majority and needs a different route for the rest',
     'The migration account should have been given access automatically', 'C'),
    ('Northgate Bank: The Account That Could Not Sign In', 7, 'What is the ongoing consequence of those channels?',
     'They were merged into public channels',
     'They were migrated without their history',
     'They were deleted at cutover',
     'They stayed in Slack under a read-only licence the bank renews annually', 'D'),
    ('Northgate Bank: The Account That Could Not Sign In', 8, 'A forty-question security review had been cleared before either migration began. What does the overnight block suggest about that review?',
     'It had been answered incorrectly by the migration team',
     'It was completed too late in the programme to be useful',
     'It examined the platforms but not the accounts the migration would actually run as',
     'It had exempted the migration from every policy already', 'C'),
    ('Northgate Bank: The Account That Could Not Sign In', 9, 'What links the security incidents and the private channels?',
     'Both were caused by the bank security regime',
     'Both were resolved within the week',
     'Both affected only the Message migration',
     'Both required somebody outside the migration team to act before work could continue', 'D'),
    ('Northgate Bank: The Account That Could Not Sign In', 10, 'Which sentence best summarises the whole briefing?',
     'Two migrations halted by a bank refusing security exemptions',
     'Two migrations where the same permission problem appeared twice, and where the fix that mattered was widening it from an account to a class',
     'A mail migration that lost eleven hours to an expired password',
     'A message migration that could not move any private channels', 'B'),
    ('Orlow Pharma: Where the Reports Go', 1, 'Where did the residency exception actually lie?',
     'In the customer own network',
     'In the destination mail platform',
     'In the reporting service, hosted in North America',
     'In the works council agreement', 'C'),
    ('Orlow Pharma: Where the Reports Go', 2, 'Why did the reports matter?',
     'They contained the content itself',
     'They contained file names, folder paths and mailbox display names',
     'They were sent to external auditors',
     'They were retained for twenty-five years', 'B'),
    ('Orlow Pharma: Where the Reports Go', 3, 'How did Julien handle the discovery?',
     'He raised it himself in the same meeting, before anyone asked',
     'He noted it in the design as a technicality',
     'He waited for the council to raise it',
     'He escalated it to the vendor first', 'A'),
    ('Orlow Pharma: Where the Reports Go', 4, 'Why was the immediate option not simply taken, given it cost nothing and needed no delay?',
     'The works council had already ruled it out',
     'The vendor did not support reports without names',
     'It would not have satisfied the residency requirement either',
     'It would have removed the detail the team needed to diagnose problems during the migration', 'D'),
    ('Orlow Pharma: Where the Reports Go', 5, 'What did validating the European instance uncover?',
     'Nothing',
     'A residency breach in the content path',
     'A performance limit at that scale',
     'A character encoding fault that mangled German file names', 'D'),
    ('Orlow Pharma: Where the Reports Go', 6, 'What is the asymmetry between the two migrations?',
     'Mail moved faster than content',
     'A mailbox has one owner, while a shared document has owners, editors and links that may have gone anywhere',
     'Content was in scope for the works council and mail was not',
     'Mail reports were generated locally', 'B'),
    ('Orlow Pharma: Where the Reports Go', 7, 'The encoding defect was worked around rather than waited out. What does the length of the vendor fix tell you about that choice?',
     'Waiting would have held the migration for most of a year',
     'The workaround was unnecessary in hindsight',
     'The vendor treated it as a low-priority cosmetic issue',
     'The defect could have been avoided by staying on the original instance', 'A'),
    ('Orlow Pharma: Where the Reports Go', 8, 'What is the state of Julien architecture-diagram recommendation?',
     'Accepted in principle and still not implemented',
     'Rejected by the works council',
     'Implemented before go-live',
     'Withdrawn by Julien', 'A'),
    ('Orlow Pharma: Where the Reports Go', 9, 'What is the general lesson the briefing draws?',
     'Works councils should approve architecture diagrams',
     'Residency commitments should exclude reporting',
     'The part that left the region was the report ABOUT the migration, not the migration',
     'German file names should be transliterated', 'C'),
    ('Orlow Pharma: Where the Reports Go', 10, 'Which sentence best summarises the whole briefing?',
     'A design that routed employee content outside Europe',
     'A residency promise that held for content on both migrations and was nearly broken by the reporting behind them',
     'A vendor defect that mangled German file names and delayed a project',
     'A pair of migrations blocked for three weeks by a works council', 'B'),
    ('Pinehurst Council: Public by Default', 1, 'What obligation sat over both migrations?',
     'A twenty-five-year retention rule',
     'A works council agreement',
     'Freedom of information: any resident may request a document or recorded communication',
     'A regulator ten-day response window', 'C'),
    ('Pinehurst Council: Public by Default', 2, 'What made the CONTENT side harder?',
     'The records manager refused to sign off',
     'The volume exceeded the SPO limit',
     'Permissions could not be mapped',
     'The two authorities had filed by opposite conventions and merging meant choosing', 'D'),
    ('Pinehurst Council: Public by Default', 3, 'What did Elena refuse to let the migration team do?',
     'Run both migrations on one plan',
     'Merge the two tenants',
     'Choose the target filing structure',
     'Publish the known limitation', 'C'),
    ('Pinehurst Council: Public by Default', 4, 'Six weeks were spent on a filing structure before any content moved. What did that buy the council afterwards?',
     'A single search that answers a resident request, rather than two that must be combined',
     'A lower storage bill across the merged estate',
     'The ability to keep both authorities conventions side by side',
     'A shorter migration overall', 'A'),
    ('Pinehurst Council: Public by Default', 5, 'What was the subtler problem on the MESSAGE side?',
     'Channel conversations were not preserved',
     'Threads flattened into single posts',
     'Guest members lost access',
     'The two authorities had different retention settings and merging means one wins', 'D'),
    ('Pinehurst Council: Public by Default', 6, 'Which option did the council choose, and why is it not free?',
     'Keep everything, which is safer for freedom of information and more expensive',
     'Delete after eighteen months, which is cheaper and creates a visible gap',
     'Keep everything, which is cheaper but riskier',
     'Delete everything older than eleven months', 'A'),
    ('Pinehurst Council: Public by Default', 7, 'Part of the deleted chat period could not be recovered. How did Elena treat that gap?',
     'She recorded and published it as a known limitation rather than leaving it to be found',
     'She extended the backfill until it was closed',
     'She treated it as acceptable and did not record it',
     'She escalated it to the regulator for a ruling', 'A'),
    ('Pinehurst Council: Public by Default', 8, 'How did Elena handle the remaining gap?',
     'She left it to be discovered',
     'She wrote it into the register as a known limitation with a published explanation',
     'She extended the backfill by six weeks',
     'She escalated it to the regulator', 'B'),
    ('Pinehurst Council: Public by Default', 9, 'What was Elena closing observation?',
     'That one plan and one register made the project possible',
     'That the two authorities should not have merged tenants',
     'That freedom of information makes migration impossible',
     'That both decisive decisions were taken by records people rather than technologists', 'D'),
    ('Pinehurst Council: Public by Default', 10, 'Which sentence best summarises the whole briefing?',
     'Two migrations delayed six weeks by a records manager',
     'Two merged-authority migrations run on one plan, where the decisions that mattered were about records rather than technology',
     'A content migration that could not merge two filing conventions',
     'A message migration that lost seven months of chat history', 'B'),
    ('Quarry Analytics: The Cost of Keeping Both', 1, 'What was Marianne framing for the programme?',
     'A go-live date',
     'A regulator deadline',
     'A target of a hundred and forty thousand dollars off annual platform spend',
     'A headcount reduction', 'C'),
    ('Quarry Analytics: The Cost of Keeping Both', 2, 'Why did pricing the thirty-day overlap change the conversation about it?',
     'It showed the overlap was cheaper than the team had assumed',
     'It proved the recovery requests were not genuine',
     'It turned a standard practice into a spend that had to justify itself',
     'It made the finance director responsible for the decision', 'C'),
    ('Quarry Analytics: The Cost of Keeping Both', 3, 'What did Ade evidence actually show about recovery requests?',
     'The average last request was at nineteen days, but two thirds could have been served from the destination',
     'Two thirds arrive after thirty days',
     'They stop after ten days',
     'They are almost never genuine', 'A'),
    ('Quarry Analytics: The Cost of Keeping Both', 4, 'What is notable about Ade giving that answer?',
     'It confirmed his recommendation',
     'It came from the customer own data',
     'It weakened his own recommendation and he gave it anyway',
     'It was disputed by the finance director', 'C'),
    ('Quarry Analytics: The Cost of Keeping Both', 5, 'What made Marianne alternative better than either of the positions that had been argued?',
     'It kept the full thirty days at a lower licence rate',
     'It covered the genuine recovery risk without paying to keep whole platforms alive',
     'It removed the need for any export at all',
     'It transferred the risk to the migration team', 'B'),
    ('Quarry Analytics: The Cost of Keeping Both', 6, 'What condition did Ade add, and what did it find?',
     'A second export to another region, which found nothing',
     'Verification by restoring three items at random, which found one incomplete export',
     'A thirty-day hold on the licences, which saved money',
     'A written waiver, which the customer signed', 'B'),
    ('Quarry Analytics: The Cost of Keeping Both', 7, 'Three of the four later requests were served from the destination. What does that pattern suggest about recovery requests generally?',
     'Most are raised too late to be actionable',
     'Most arrive within the first ten days',
     'Most concern content that was never in scope',
     'Most are people unable to find content that is already there, rather than content that is missing', 'D'),
    ('Quarry Analytics: The Cost of Keeping Both', 8, 'Why does the fourteenth channel matter?',
     'It was the largest channel in the export',
     'It was the only channel that failed verification',
     'It proved the twelve had been chosen badly',
     'The process would not have covered it and an engineer rounding up did', 'D'),
    ('Quarry Analytics: The Cost of Keeping Both', 9, 'What was the final saving against the target?',
     'A hundred and fifty-two thousand, twelve thousand above target',
     'Nine hundred dollars',
     'Eleven thousand, well short',
     'A hundred and forty thousand, exactly on target', 'A'),
    ('Quarry Analytics: The Cost of Keeping Both', 10, 'Which sentence best summarises the whole briefing?',
     'Two consolidations run to a savings target, where an honest answer against his own recommendation produced a cheaper plan that still covered the risk',
     'Two consolidations that cut spend by decommissioning immediately',
     'A migration that lost content because the overlap was too short',
     'A finance director overruling migration advice at the cost of four recoveries', 'A')
    ) AS v(story_title, ordinal, q, a, b, c, d, correct)
JOIN listening_story s ON s.level = 3 AND s.title = v.story_title
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-listening-bank-v3');

INSERT INTO seed_state (seed_key) VALUES ('l3-listening-bank-v3') ON CONFLICT DO NOTHING;
