-- =====================================================================
-- Level 3 Speaking: spoken ANSWER questions.
--
-- This REPLACES the 300 read-aloud sentences that were seeded here on 2026-09-02. Levels 1 and 2
-- are unchanged and still repetition tasks; Level 3 is now a different assessment:
--
--   Levels 1-2   a sentence appears, the candidate reads it aloud, and the score comes from
--                comparing the transcript with that sentence.
--   Level 3      a two-workstream migration scenario appears with a question about it, the
--                candidate answers in their own words, and AiService.scoreSpokenAnswer judges
--                the ANSWER -- did they find the real dependency, separate blockers from what
--                can wait, recommend something defensible -- alongside the English they said it
--                in. There is no model wording, and a right answer phrased plainly beats a
--                fluent one that misreads the situation.
--
-- 12 sets of 5 questions. Five, not ten: an analytical answer runs one to two minutes, so a set
-- of ten would be a fifty-minute section. The Level 3 clock is 25 minutes (SpeakingService),
-- which allows reading, thinking, answering and one re-record per question.
--
-- EVERY QUESTION CARRIES TWO CONNECTED WORKSTREAMS, and they are connected by a real migration
-- dependency -- a shared change window, an identity that both depend on, a source freeze that
-- one needs and the other cannot yet accept. A candidate who discusses only one has answered
-- half, and the scoring prompt says so explicitly.
--
-- THE ANSWER IS NEVER STATED IN THE QUESTION. Symptoms are given; the cause is not. A candidate
-- who has memorised terminology can repeat the scenario back and will score below 40 on
-- accuracy for it. The questions are written so that an experienced engineer has to think before
-- answering, which is the only way the section can tell the two apart.
--
-- Question types are mixed within each set so no set is five of the same shape: troubleshooting,
-- root cause, sequencing, risk triage, go or no-go, cutover coordination, post-migration
-- investigation, explaining a limitation to a non-technical customer, dependency analysis, and
-- recommending between options.
--
-- Combinations are drawn from the migration documentation tool and rotated deliberately: no
-- pairing is used twice, and the failure patterns vary -- path length, external identity and
-- permissions appear once or twice each rather than in every scenario.
--
-- Avoid apostrophes: these are single-quoted SQL literals.
--
-- The old read-aloud rows are cleared once, guarded by this marker, the same way data.sql
-- refreshes a bank it has already seeded.
-- =====================================================================
DELETE FROM speaking_sentence WHERE level = 3
  AND NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-speaking-questions-v1');

-- ---------- Sets 1 to 4 ----------
INSERT INTO speaking_sentence (created_at, updated_at, text, set_number, level, difficulty)
SELECT now(), now(), v.text, v.set_number, 3, 'HARD'
FROM (VALUES
    -- Set 1: Slack to Teams + Shared Drive to SPO
    ('A customer is moving 1,400 users from Slack to Teams, and in the same programme 40 terabytes from Google Shared Drives to SharePoint Online. Both cutovers are booked into one change window because the customer negotiated a single production freeze with their operations board. Four days before go-live, the content pre-stage is at 82 percent and slowing, while the Slack export has finished early. The migration lead wants to keep the single window. Walk me through how you would assess whether that window is still realistic, what you would measure before deciding, and what you would put to the customer.', 1),
    ('Two workstreams are running for the same customer: a Teams tenant-to-tenant migration and a SharePoint tenant-to-tenant migration between the same two tenants. After the first wave, users report that files posted in migrated channels open correctly for some people and return access denied for others, with no obvious pattern by department. The SharePoint workstream reports no failures at all and its reconciliation matches. How would you investigate this, and what would you expect to find given that both workstreams are moving between the same two tenants?', 1),
    ('A customer has finished the Slack to Teams migration for 600 users and is two weeks from the SharePoint cutover. During that gap, staff are working in Teams while their documents are still in Google Shared Drives, and they are sharing links to those Drive files inside Teams channels. The customer asks whether anything needs to be done about that before the content migration runs. What is your assessment, and what would you recommend to them?', 1),
    ('You are asked to sequence two workstreams for an acquisition: a Slack to Teams migration for 900 users, and a Shared Drive to SPO migration of their project libraries. The customer wants content first so that people find their files in the new place from day one. Your colleague argues for messaging first. Which would you sequence first, what does your choice depend on, and what would you need to confirm with the customer before committing to it?', 1),
    ('A customer escalates that after the Slack to Teams cutover, a department cannot find three years of conversation history, while their SharePoint content migrated with no reported issues. The migration logs show the channels in question completed successfully with no errors. Explain how you would approach this with the customer on a call, what you would want to establish before offering an explanation, and how you would set expectations without committing to a cause you have not yet confirmed.', 1),

    -- Set 2: Gmail to Outlook + OneDrive tenant-to-tenant
    ('A customer is moving 2,000 mailboxes from Gmail to Outlook and, in parallel, their OneDrive content between two Microsoft tenants after a reorganisation. The mail migration is in its second wave and running to plan. The OneDrive workstream has completed its initial copy but the delta pass keeps reporting items it has already moved. The customer has asked whether both can still cut over on the same weekend. What would you check first, and how would you frame the risk to the customer?', 2),
    ('During a Gmail to Outlook migration, several users report that mail they filed under multiple labels now appears in only one folder, while others say their filing looks complete. At the same time, the OneDrive tenant-to-tenant workstream reports that a group of users has no content at all in the destination. Both issues were raised in the same escalation. Are these one problem or two, how would you establish that, and what would you tell the customer while you find out?', 2),
    ('A customer wants to run the final delta pass for a OneDrive tenant-to-tenant migration during the same change window as their Gmail to Outlook MX cutover, to keep disruption to one evening. Their IT director has approved the plan. Talk me through the dependencies between those two activities, which of them you would be comfortable running together, and what you would raise before the go-ahead.', 2),
    ('Two weeks after a Gmail to Outlook cutover and a OneDrive tenant move, a customer reports that a shared mailbox their finance team relies on is accessible to nobody, and separately that a set of files shared with an external auditor can no longer be opened by that auditor. Both were working before the migration. How would you investigate each, and what do the two situations have in common that would shape how you explain them to the customer?', 2),
    ('You are on a go or no-go call. The Gmail to Outlook workstream has completed user acceptance testing with two open defects, both cosmetic. The OneDrive tenant-to-tenant workstream has completed its copy but post-migration validation has only been run against 3 of 12 departments, and the customer business owner is on leave until after the planned cutover date. What is your recommendation, and how would you justify it to a customer who wants to proceed?', 2),

    -- Set 3: Teams to Google Chat + SharePoint tenant-to-tenant
    ('A customer is moving from Teams to Google Chat for 800 users while also consolidating two SharePoint tenants into one. Three days before the messaging cutover, the SharePoint workstream discovers that a site collection used by the same 800 users will not complete its copy before the messaging change window. The customer asks whether the messaging cutover can simply go ahead as planned. How would you answer, and what would you want to know before answering?', 3),
    ('After a Teams to Google Chat migration, users report that conversations they remember as threaded now read as a flat list, and that files they had shared inside those conversations are no longer reachable from the message. The SharePoint tenant-to-tenant workstream that ran alongside it reports full success. Explain what is likely happening in each case, how you would confirm it, and how you would explain the difference to a customer who believes both are the same fault.', 3),
    ('A customer is running two workstreams for the same 800 people: a Teams to Google Chat migration, and a consolidation of two SharePoint tenants into one. The Chat workstream took six weeks before a single message moved, while the SharePoint workstream started copying two days after kickoff. Both are now complete and both came in on budget. At the steering committee, a director with no technical background asks why one needed six weeks of preparation and the other needed two days. How would you explain that difference so the committee can use it when they budget the next programme?', 3),
    ('During a Teams to Chat cutover, the migration account loses access partway through a wave and the job stops. The same account is used by the SharePoint tenant-to-tenant workstream, which is mid-delta at the time and also stops. Both resume after the account is restored. The customer wants to know whether this will happen again in the final wave. What would you investigate, and what would you commit to before the next wave?', 3),
    ('A customer has 200 external collaborators who currently work inside Teams channels and also hold access to documents in the SharePoint tenant being consolidated. The customer wants to migrate messaging first and deal with the external collaborators later, after go-live. Assess that approach across both workstreams, and give your recommendation with the reasoning a customer would need to accept it.', 3),

    -- Set 4: Outlook tenant-to-tenant + OneDrive to SharePoint
    ('An acquisition requires 1,200 mailboxes to move between Microsoft tenants, and the same users OneDrive content to be reorganised into SharePoint team libraries. Identity mapping for internal users is complete. The customer wants to cut over mail this weekend and run the content workstream a month later. Their security team has just enabled a conditional access policy that blocks sign-in from unrecognised locations. What is your assessment of the plan as it stands, and what would you do before the weekend?', 4),
    ('A tenant-to-tenant mailbox migration completed on Saturday. On Monday, a group of users can send and receive mail but cannot open any document link a colleague sends them, while the OneDrive to SharePoint workstream reports that all content moved and validated. Nothing in either migration log shows an error. Talk me through how you would investigate this, and what you would rule out first.', 4),
    ('You are planning a change window that has to contain a tenant-to-tenant mailbox cutover and the final incremental copy of a OneDrive to SharePoint migration. The customer has given you six hours and will not extend it. Describe how you would order the activities inside that window, where the dependencies are, and what you would have ready in case one of them overruns.', 4),
    ('Post-migration validation after a tenant-to-tenant mailbox move shows every mailbox present and item counts matching. Two weeks later the customer reports that meeting invitations sent by a group of staff show the wrong organiser, and separately that a document library migrated from OneDrive has lost its permissions for one team. The customer believes both prove the migration was rushed. How would you respond to that, and what would you actually investigate?', 4),
    ('A customer asks you to recommend between two approaches for their acquisition: migrate mailboxes and content together in one weekend for 1,200 users, or run mail first and content four weeks later with a period of coexistence in between. Both are technically possible. Give your recommendation, the trade-offs on each side, and the question you would need answered before you would commit to either.', 4)
    ) AS v(text, set_number)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-speaking-questions-v1');

-- ---------- Sets 5 to 8 ----------
INSERT INTO speaking_sentence (created_at, updated_at, text, set_number, level, difficulty)
SELECT now(), now(), v.text, v.set_number, 3, 'HARD'
FROM (VALUES
    -- Set 5: Google Chat to Teams + Shared Drive to OneDrive
    ('A customer is migrating from Google Chat to Teams for 1,100 staff while moving their Shared Drive content into individual OneDrive areas. Two days into the content pre-stage, throughput has dropped to a third of what the pilot achieved, and the engineer on the job believes the destination is throttling. The messaging workstream is unaffected and on schedule. What would you want to see before you accepted that explanation, and what would you do next?', 5),
    ('After a Chat to Teams cutover, an operations team reports that their daily handover, which they used to post as replies under one message, is now spread across the channel as separate posts. In the same week, the Shared Drive to OneDrive workstream reports that 6 percent of files did not migrate. The customer has escalated both together as evidence of a failed migration. How would you separate these two in a conversation with the customer, and what would you commit to for each?', 5),
    ('A customer wants their Shared Drive content moved into OneDrive personal areas so that each file has a single owner. Their Chat to Teams migration is already complete. During discovery you find that many of those drives are used daily by whole teams rather than individuals. Explain how you would raise this with the customer, what you would recommend, and what you would need from them before the content workstream could proceed.', 5),
    ('You are three weeks from go-live on a Chat to Teams migration and a Shared Drive to OneDrive migration for the same 1,100 users. The customer proposes freezing the source Shared Drives now, a fortnight early, so that the content copy has a stable source. Assess that proposal across both workstreams, including what it would cost the business, and give your recommendation.', 5),
    ('A customer has completed a Chat to Teams migration for 1,100 users, and their Shared Drive to OneDrive workstream is a week from cutover. The content design states that files move in full but a number of existing sharing arrangements will have to be reissued, while the messaging migration preserved every conversation exactly. The business owner, who is not technical, has to present both outcomes to her leadership and does not understand why one is complete and the other is not. How would you explain the difference to her, and what would you give her that she can repeat accurately?', 5),

    -- Set 6: Slack to Google Chat + SharePoint to Shared Drive
    ('A customer is moving from Slack to Google Chat and, in the same programme, from SharePoint Online into Google Shared Drives. The messaging pilot has completed and the engineering team is unhappy: their runbooks, written as formatted Slack posts, arrived as plain text. The content pilot has not started. Explain what you would do about the pilot finding, and what you would check in the content workstream before it starts, given what the messaging pilot revealed.', 6),
    ('Two workstreams are live for the same customer: Slack to Google Chat, and SharePoint to Shared Drive. The customer legal team runs date-range searches across both for a regulatory request and reports that results from before the migration no longer match results from after it. Both migrations reported successful completion. How would you approach this, what would you examine in each workstream, and what would you be careful not to promise?', 6),
    ('A customer wants to decommission both source platforms two weeks after go-live to stop licence spend, across a Slack to Chat migration and a SharePoint to Shared Drive migration. Your own data from previous projects suggests genuine recovery requests continue past that point. Make the case to the customer, including the part of your evidence that supports their position, and say what you would recommend.', 6),
    ('During a SharePoint to Shared Drive migration, a set of documents converts to Google format on arrival and a business team reports that comments and tracked changes are missing. In parallel, the Slack to Chat workstream is holding at 95 percent with a group of private channels not yet moved. The customer asks which of these should worry them more. How would you answer, and what would you do about each?', 6),
    ('You are asked to give a go or no-go recommendation for a combined cutover: Slack to Chat messaging, and SharePoint to Shared Drive content, in one weekend. Messaging has passed validation. Content has an open item where 4,000 files failed on their names and have not yet been remediated, and the customer says those files belong to an archive nobody uses. What is your recommendation and how would you defend it?', 6),

    -- Set 7: Teams tenant-to-tenant + Shared Drive tenant-to-tenant
    ('Two companies have merged and both run Google and Microsoft side by side. You are moving Teams between two Microsoft tenants and Shared Drives between two Google tenants, for the same 700 people. The customer regards both as simple because nothing changes platform. Explain where you actually expect the difficulty to be, and how you would set expectations with a sponsor who believes this is a copy job.', 7),
    ('After a Teams tenant-to-tenant migration, a group of users find channels they own are now owned by somebody else, and a smaller group find channels missing entirely. The Shared Drive tenant-to-tenant workstream reports that 14 drives ended up owned by a service account rather than by a person. Nobody reported an error in either migration. What single underlying issue would you investigate first, and how would you confirm it?', 7),
    ('A customer asks you to run the Shared Drive tenant-to-tenant copy and the Teams tenant-to-tenant cutover in the same weekend to reduce the number of production changes. During discovery you learn that both depend on the same set of user accounts being created in the destination tenants beforehand, and that account creation is being done by the customer own IT team. What would you clarify with them, and how would that change the plan?', 7),
    ('Halfway through a tenant-to-tenant programme, the customer HR team supplies an updated staff list showing 90 people who have left since discovery. Both the Teams and Shared Drive workstreams have already had their mapping files signed off. Talk me through the impact on each workstream, what you would do about the content and conversations belonging to those 90 people, and what you would ask the customer to decide.', 7),
    ('A customer is unhappy that a same-platform tenant-to-tenant programme has taken nine days longer than a cross-platform project they ran last year, and says the estimate must have been wrong. Both the Teams and Shared Drive workstreams are affected. How would you handle that conversation, and what would you actually examine before responding to the claim?', 7),

    -- Set 8: Gmail tenant-to-tenant + SharePoint to OneDrive
    ('A customer is consolidating two Google tenants after a merger, moving 900 mailboxes, and at the same time reorganising SharePoint site content into OneDrive personal areas for the same users. The mail consolidation cannot start until account mapping is signed off, and the content workstream has already begun. The customer wants both complete before quarter end, which is five weeks away. Assess whether that is achievable and what you would do to protect the date.', 8),
    ('Users report after a Gmail tenant-to-tenant consolidation that delegated access to colleagues mailboxes no longer works, and separately that files they had shared from SharePoint before the OneDrive move can no longer be opened by the people they shared them with. Both were working the week before. What is the likely common factor, how would you verify it, and what would you do to resolve each?', 8),
    ('You are planning the final cutover for a Gmail tenant-to-tenant consolidation. The customer also wants the SharePoint to OneDrive content workstream to finish first so that staff have their files before mail moves. Your content lead says the final content pass needs the source read-only for six hours. The mail cutover needs a different six hours the same night. Talk me through how you would coordinate the two and what you would tell the customer about the risk.', 8),
    ('A customer reports two weeks after go-live that a number of documents in OneDrive show a migration service account as the last editor and that some Gmail messages appear with a different sender name than the original. Their compliance officer has asked whether the audit trail has been compromised. How would you respond, what would you verify, and how would you explain it to a compliance audience?', 8),
    ('You have to recommend whether to run a Gmail tenant-to-tenant consolidation as one cutover for 900 users or as three waves of 300. The customer helpdesk has four people. The SharePoint to OneDrive workstream is running in parallel either way and finishes in week three. Give your recommendation, the reasoning, and what would make you change your mind.', 8)
    ) AS v(text, set_number)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-speaking-questions-v1');

-- ---------- Sets 9 to 12 ----------
INSERT INTO speaking_sentence (created_at, updated_at, text, set_number, level, difficulty)
SELECT now(), now(), v.text, v.set_number, 3, 'HARD'
FROM (VALUES
    -- Set 9: Outlook to Gmail + OneDrive to Shared Drive
    ('A customer is moving 900 mailboxes from Outlook to Gmail and the same peoples OneDrive content into Google Shared Drives. Two weeks after the mail cutover, the helpdesk is taking a steady stream of calls that staff describe as mail going missing, while the content workstream has not started. The mail migration reported no failures and item counts reconcile. What would you investigate, and what would you ask the helpdesk to capture for you?', 9),
    ('You are advising a customer who wants their OneDrive content moved into Shared Drives before the Outlook to Gmail cutover, so that staff have one change rather than two. Your colleague recommends the opposite order. Set out the dependency between the two workstreams as you see it, say which order you would choose, and explain what would make the other order the right one.', 9),
    ('During an Outlook to Gmail migration a business team reports that recurring meetings appear twice in their new calendars. In the same period the OneDrive to Shared Drive workstream reports that a folder structure arrived with its files intact but its access restricted to fewer people than before. The customer has asked for a single root cause analysis covering both. How would you respond to that request, and how would you actually approach each?', 9),
    ('You are four weeks from cutover on an Outlook to Gmail migration for 900 staff, with their OneDrive content moving into Google Shared Drives in the same programme. The user communication drafted for the mail workstream tells every member of staff they will need to rebuild their own mail rules, and the equivalent note for the content workstream asks them to do nothing at all. An executive has seen both and wants to know whether his team is being asked to absorb an avoidable cost. Explain the difference to him and say what you would offer to reduce the impact.', 9),
    ('You are running a go or no-go call for an Outlook to Gmail cutover. Content migration to Shared Drives is complete and validated. Mail testing is complete except that the pilot group never tested delegate access, and three of the customer executives rely on assistants who manage their calendars. The customer wants to proceed. What is your recommendation and what would you require before agreeing to go?', 9),

    -- Set 10: Slack workspace consolidation + OneDrive tenant-to-tenant
    ('A customer is consolidating three Slack workspaces into one and moving OneDrive content between two Microsoft tenants for the same 500 people. During the Slack pre-check the team finds that all three workspaces contain channels with identical names. The OneDrive workstream is ready and waiting on a date. The customer wants both done in the same week. What would you resolve before either can start, and how would you put that to the customer?', 10),
    ('Two days after a Slack consolidation, users report that some conversations they expected to find are missing, and the OneDrive tenant-to-tenant workstream reports a group of users whose content arrived but who cannot open it. The customer suspects one migration has damaged the other. Explain how you would establish whether these are related, and what you would say to the customer while the investigation runs.', 10),
    ('A customer is consolidating three Slack workspaces into one for 500 people, and is midway through it: two workspaces have moved and the third is scheduled for next week. The OneDrive tenant-to-tenant workstream for the same 500 people is ready and has been waiting on a date for a fortnight. The customer has asked whether the content migration can start now rather than wait, arguing that the two touch different systems. Talk me through whether you agree, what dependencies exist between them if any, and what you would want in place before running them concurrently.', 10),
    ('After a Slack consolidation and a OneDrive tenant move, the customer reports that external partners who used to collaborate with them can no longer do either: they cannot post in the consolidated workspace and cannot open the files they were sent. The customer regards this as one failure. How would you explain what has happened, and what would you need from the customer to fix it?', 10),
    ('You are asked to recommend how long to keep the three source Slack workspaces and the source OneDrive tenant alive after go-live. Licences for both cost real money and the customer finance director is pressing to switch everything off at day seven. Make your recommendation, including what evidence you would bring, and how you would handle it if the customer overrules you.', 10),

    -- Set 11: Google Chat tenant-to-tenant + Shared Drive to SharePoint
    ('A customer is consolidating two Google tenants worth of Chat conversations and, separately, moving Shared Drive content into SharePoint Online. Their compliance officer has told you that four legal holds cover conversations in the source Chat tenant, and that retention labels must survive on the content side. Explain how each of those requirements affects its workstream, and what you would establish before either migration is scheduled.', 11),
    ('Midway through a Shared Drive to SharePoint migration, a business unit reports that documents they expect to be restricted are visible to more people than before. The Chat tenant-to-tenant workstream running alongside reports no issues. The customer wants to stop both migrations immediately. How would you respond in that moment, what would you investigate, and how would you decide whether stopping is necessary?', 11),
    ('A customer is consolidating two Google Chat tenants and moving Shared Drive content into SharePoint Online, and both fall under an audit regime where any message or document can be requested. Four legal holds mean a block of conversations will stay in the source tenant rather than move with the rest, and on the content side the documents arrive unchanged while the way they are shared does not. Their records manager has to defend both outcomes to an auditor and has asked you to explain them. How would you explain each, and what would you put in writing for her?', 11),
    ('Two workstreams share a change window: a Chat tenant-to-tenant cutover and the final delta pass of a Shared Drive to SharePoint migration. On the day, the content delta is running four hours behind and will overlap the messaging cutover. Describe how you would handle that situation on the night, who you would involve, and what you would decide.', 11),
    ('A programme is eight days from go-live: a Chat tenant-to-tenant consolidation for 700 users, and a Shared Drive to SharePoint migration of 18 terabytes for the same people. The punch list has four open items -- retention rules not yet rebuilt at the destination, 30 external collaborators not yet re-invited, 2,000 files failing on their names, and the migration account access expiring in ten days. The customer wants to hold the date. Which of those would you treat as blockers to go-live and which can run into hypercare, and what is your reasoning for each?', 11),

    -- Set 12: Teams to Google Chat + Gmail to Outlook (message + mail, opposite directions)
    ('A customer group has decided that messaging moves from Teams to Google Chat while mail moves from Gmail to Outlook, because two parts of the business made separate decisions. Both programmes run in the same quarter for the same 1,000 staff. The customer sponsor asks you whether these two decisions can coexist. Explain what genuinely conflicts and what does not, and what you would put in place to keep the user experience coherent.', 12),
    ('During a Teams to Chat migration and a Gmail to Outlook migration running in parallel, users start reporting that meeting invitations sent from the new mail platform do not appear in the calendars of colleagues who have already moved messaging. Both migrations report normal operation. How would you investigate this, and what would you check about the sequence in which these users were migrated?', 12),
    ('A customer of 1,000 staff is moving messaging from Teams to Google Chat and mail from Gmail to Outlook, and wants both cutovers in the same week to get the disruption over with. Their helpdesk has six people, no weekend cover, and handled roughly 90 calls after a much smaller migration last year. Neither workstream depends on the other technically. Assess that plan, describe the load you would expect from each workstream and when it would arrive, and give your recommendation with the reasoning a sponsor would accept.', 12),
    ('Post-migration, a customer reports that staff are receiving mail correctly in Outlook but continue to send messages in Teams, which is no longer the supported platform, and that files shared in those Teams conversations are not reaching the people who need them. The migrations themselves are complete and validated. How would you approach this, and is this a migration problem?', 12),
    ('You have to recommend a sequence for a customer moving messaging from Teams to Chat and mail from Gmail to Outlook. Doing mail first means a period where staff have new mail and old messaging; doing messaging first inverts that. Neither is free. Give your recommendation, explain what your choice depends on, and name what you would need to know about this customer before you committed to it.', 12)
    ) AS v(text, set_number)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-speaking-questions-v1');

INSERT INTO seed_state (seed_key) VALUES ('l3-speaking-questions-v1') ON CONFLICT DO NOTHING;
