-- =====================================================================
-- Level 3 Writing prompt bank.
--
-- REWRITTEN AGAINST THE MIGRATION DOCUMENTATION (v2). The previous bank repeated the same three
-- factual errors as the speaking bank -- Slack to Chat described as losing formatting when it is
-- one of the RICHER combinations, Chat to Teams threads described as arriving flat when channel
-- threads are Yes for that pair -- and drew on six platform names in total. Every prompt below
-- names a combination and a limitation the feature matrices actually record, and between them
-- they cover Box, Dropbox, Egnyte, ShareFile, Amazon WorkDocs, NFS/SMB, Azure Blob, Whiteboard,
-- Workplace from Meta, LinkEX and all twelve message combinations.
--
-- 101 prompts: 51 Customer Email and 50 Escalation Reply. WritingService serves one from each
-- pool per attempt, and ContentAssignmentService excludes anything a candidate has already been
-- given, so nobody repeats their own tasks and the pools are large enough that sharing is rare.
--
-- BOTH TASKS ARE CUSTOMER REPLIES. That is the deliberate difference from Levels 1 and 2, where
-- the second task is an internal document. At this level the candidate writes to the customer
-- twice, because that is the piece of writing that carries commercial risk.
--   Pool 1, "Customer Email"      -- the routine reply: explaining, confirming, setting a date.
--   Pool 2, "Escalation Reply"    -- the reply written when the customer is unhappy, worried,
--                                   escalating, or asking for something that cannot be given.
--
-- EVERY PROMPT CARRIES TWO MIGRATIONS. The customer raises two things at once and a reply that
-- answers only the louder of the two is an incomplete answer. That is what the completeness mark
-- is for, and the instruction lines name both threads on purpose.
--
-- A NOTE ON WHAT IS TRUE. Each prompt states the real cause after the customer complaint, so a
-- candidate is not asked to diagnose -- they are asked to explain and to hold a position. The
-- causes are documented ones: ShareFile has no delta in any destination; mail supports no second
-- delta; archived channels are No in all twelve message combinations; reactions survive only
-- Slack to Slack, Slack to Chat, Chat to Teams and Chat to Chat; Google file version timestamps
-- cannot be overridden; Egnyte names are capped at 200 characters; Outlook to Gmail cannot carry
-- rules, categories, Notes or contact groups; Dropbox Paper tables cap at 62 or 63 columns; Box
-- Notes lose tables and mentions; whiteboards never carry comments or voting; and four
-- combinations are marked do-not-confirm-with-clients.
--
-- Avoid apostrophes: these are single-quoted SQL literals.
-- =====================================================================
DELETE FROM writing_prompt WHERE level = 3
  AND NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-writing-bank-v2');

-- ============================ POOL 1: Customer Email (51) ============================
INSERT INTO writing_prompt (created_at, updated_at, category, prompt, level, difficulty)
SELECT now(), now(), 'Customer Email', v.prompt, 3, 'HARD'
FROM (VALUES
    ('Priya, an IT manager at TechNova, writes with two questions. Her staff say about 200 Slack channels are missing in Teams, and her finance team cannot open files that were shared by link before the Box to OneDrive move. The channels are private ones whose owners never added your migration account, and they are still in Slack. The links did migrate but now resolve to named members rather than to anyone holding the URL. Reply to Priya. Deal with both, explain each in plain words, say who has to act on each, and give a date for the channels.'),
    ('A customer sponsor asks why his Gmail to Outlook cutover finished on time while the Egnyte to SharePoint copy is four days late, when both were quoted for the same weekend. The mail side was straightforward. The content side ran long because several thousand files breached the 200-character name limit at the destination and had to be renamed. Reply to him. Explain why the two differ without technical jargon, give the new finish date, say what is being done now, and confirm the mail side needs nothing further.'),
    ('An operations lead reports that the reactions her team used to acknowledge shift handovers are missing from their migrated Teams channels, and in the same email asks when her department SharePoint libraries will be visible. Reactions are not carried on Slack to Teams and cannot be recovered. Her libraries migrated on Saturday and sit under a new site name she has not been told about. Reply to her. Be straight about the reactions, tell her where the libraries are, and give her something practical for the handover process.'),
    ('The programme manager asks two things in one message: whether the 40 supplier guest accounts in the Teams tenant move have been re-invited, and whether the delta pass on the Dropbox to Google Shared Drive workstream has run. The guests are being invited in waves and 26 of 40 have accepted. The delta ran overnight and cleared 1,900 changed files. Reply to him. Give both numbers plainly, say what remains on each, name what you need from his procurement team, and set the next update.'),
    ('A finance director writes that his team has lost their email rules after the Outlook to Gmail move and, in the same email, that a shared drive he expected to see is not there. Outlook rules cannot be migrated because Microsoft does not expose them through the API, and each user rebuilds their own; there is a published recipe for the twenty most common. The shared drive is out of scope in the signed statement of work. Reply to him. Be clear about both, avoid sounding defensive, offer the recipe, and set out what a change request would involve.'),
    ('A customer IT director asks for a status on two workstreams before her board meeting tomorrow: the Slack to Google Chat migration and the SharePoint to SharePoint tenant consolidation. Slack to Chat is complete for 900 users, with user mentions arriving in a reduced form because Google Chat cannot fully reproduce them. The consolidation is 60 percent done and on schedule for Friday. Reply to her. Give each in two lines, be honest about the mentions, state what she can tell her board, and offer to join the call.'),
    ('A customer asks you to confirm two things in writing before he signs: that his ShareFile content will get a top-up copy the night before go-live, and that his Teams to Slack messages will keep their original timestamps. Neither is possible. ShareFile supports no delta in any destination, and Teams to Slack posts messages live because Slack has no import mode. Reply to him. Say clearly what cannot be done, explain what you will do instead for each, and keep the deal alive.'),
    ('The customer project manager asks for a plain-English summary of what will and will not survive the Workplace from Meta to Google Chat move, and separately whether the My Drive to OneDrive copy has finished. Posts, chats, group messages, attachments and reactions on posts do migrate. Threads on channels and direct messages, custom emoji and bot integrations do not. The content copy finished on Tuesday and link remediation runs on Thursday. Reply to her. Cover both, keep the list readable, and say what she should tell staff before Thursday.'),
    ('A customer sponsor asks why the Amazon WorkDocs to SharePoint copy produced a wave of sharing notifications to staff on Saturday morning, and in the same note asks whether the Slack to Slack workspace move preserved pinned messages. Email notifications cannot be suppressed on that content combination. Pinned messages did survive, because Slack to Slack is the one combination that carries them. Reply to him. Explain the notifications without blaming the platform, confirm the pins, and say what you will do differently for the next wave.'),
    ('A customer asks for a single date when both his migrations will be finished so he can book a company announcement. The NFS file server to SharePoint copy completes on the 14th. The Outlook to Outlook mailbox move completes on the 18th, and there will be no second pass afterwards because mail does not support a second delta. Reply to him. Give one honest date rather than the earlier of the two, explain the constraint on the mail side, and tell him what has to stop happening in the source before the 18th.'),
    ('A department head writes that her team can see all their Box files in Google Drive but the review comments they left on them are gone, and asks separately when their Mural boards will be in Miro. In-line comments do migrate on Box to Google, so this needs checking rather than explaining away. The boards migrate on Friday, and comments on boards do not migrate at all. Reply to her. Say what you will check and by when on the first, and set expectations on the second before it happens.'),
    ('The customer asks two questions in one email: whether the Chat to Teams migration kept the reactions their staff use to vote on proposals, and whether the Dropbox to Azure Blob archive can be searched by permission. Reactions do migrate on Chat to Teams. The Azure archive is a data dump and carries no permissions at all. Reply to them. Confirm the good news briefly, be clear about the archive, and propose how they should search it instead.'),
    ('A customer wants to know why you have advised against Box to Box for their internal consolidation, when they can see both tenants and it looks like the simplest job on the list. The combination is marked in your documentation as not available in the current code and not to be confirmed with clients. Their other workstream, Gmail to Gmail, is straightforward. Reply to them. Explain the position without alarming them, offer the routes that are supported, and confirm the mail side.'),
    ('The customer compliance officer asks for two confirmations: that the Egnyte to Google Shared Drive move preserved in-line comments, and that the Teams to Teams consolidation preserved the record of which messages were edited. Comments did survive, because Egnyte carries them to its Google destinations. The Edited label is not migrated. Reply to her. Confirm the first, be precise about what the second means for her records, and suggest what she can put in place instead.'),
    ('A customer sponsor asks you to explain, for his steering committee, why the Slack to Teams workstream took six weeks before a single message moved while the Box to SharePoint copy started two days after kickoff. The message side needed a pre-scan, user mapping and a private-channel access exercise; the content side did not. Reply to him. Explain both in language a non-technical committee can follow, and give him one sentence he can use when budgeting the next programme.'),
    ('The customer asks whether they can keep their file server online read-only for six months after the NFS to SharePoint cutover, and separately whether the Slack to Existing Teams move will bring across their direct messages. The file server question is theirs to decide and costs them licence and support. Direct messages are not migrated into an existing Teams tenant at all. Reply to them. Answer both, be clear which is a choice and which is a limit, and say what you would do about the messages.'),
    ('A customer team lead writes that half her people can see the migrated SharePoint library and half cannot, and in the same email asks why the Chat to Chat move did not bring their pinned messages. The library permission is inherited from a group her team was never added to. Google Chat has no pinned message concept, so there was nothing to carry. Reply to her. Fix the first with a clear action and owner, explain the second, and offer an alternative for how they flag important messages.'),
    ('The customer wants to bring their migration forward by a week because a lease ends. The Dropbox to SharePoint content can be pre-staged and would cope. The Gmail to Outlook mail cutover cannot, because the label mapping work is not finished and there is no second delta to catch what is missed. Reply to them. Say what can move and what cannot, do not present it as a flat refusal, and set out what you would need to make the earlier date possible.'),
    ('A customer sponsor asks for the status of two things his board asked about: the LinkEX remediation of broken links in the migrated Google content, and the Workplace from Meta closure date. The link scan has run and found 14,000 links to repair, with the fix pass booked for Wednesday. Workplace can close once the customer confirms nobody needs the channel threads, which do not migrate. Reply to him. Give both statuses, and make clear what decision you need from him and by when.'),
    ('A customer asks why their ShareFile migration is quoted as a single weekend with no top-up, when their previous vendor offered incremental syncs. ShareFile supports no delta in any destination, so the copy happens once and the source must be frozen. Their Slack to Chat workstream does support repeated delta passes. Reply to them. Explain the difference between the two workstreams, say what freezing the source means in practice for their staff, and propose the cutover approach.'),
    ('The customer asks two things: when the Egnyte to OneDrive copy will show folder structure the way it looks today, and whether the Teams to Chat move brought their file attachments. Folder display is not supported on that Egnyte destination, so the structure is there but does not render as it does in Egnyte. Attachments did migrate. Reply to them. Set the right expectation on the first without sounding evasive, confirm the second, and offer a short call if they want to see it.'),
    ('A customer department manager writes that the checklists inside their migrated Box Notes have lost their formatting in Google Docs, and separately asks when their Lucid boards arrive in Miro. Checklist and list formats are known not to survive that conversion. The boards migrate on Thursday and will lose their frames, icons and any files placed on them. Reply to her. Be honest about both, tell her what to do before Thursday, and avoid promising a fix you cannot deliver.'),
    ('The customer asks you to confirm the two dates in their communications plan: mail cutover on the 8th and content cutover on the 15th. Both are correct. He also asks you to add a line saying users can request a re-run if anything is missing. On the mail side that is not possible, because a second delta will duplicate calendar events and contacts. Reply to him. Confirm the dates, explain why that line has to change, and give him wording he can use instead.'),
    ('A customer asks for reassurance about two things before signing: that the Box to Google move will keep who can see which file inside a shared folder, and that the Slack to Chat move will keep the code blocks in their engineering runbooks. Inner file permissions are supported on that content combination. Slack to Chat carries code format, block quote and code block. Reply to them. Confirm both accurately, avoid overclaiming beyond what you know, and name one thing they should test in the pilot.'),
    ('The customer wants to know why the Google Shared Drive to SharePoint copy shows every document version with the same date. Google file versions cannot carry their original timestamps into the destination and there is no API to override them. In the same email they ask whether the Chat to Slack workstream is on track; it is, and finishes Friday. Reply to them. Explain the version dates plainly, say what you can offer as evidence of the original dates, and confirm the other workstream.'),
    ('A customer asks two things about their acquisition programme: whether the 900 mailboxes moving Outlook to Outlook will keep their flags and importance markers, and whether the SharePoint to SharePoint move will keep external sharing to their auditors. Flags and both importance levels survive that mail direction. External shares are supported on the content side but the auditors will need to accept a new invitation. Reply to them. Confirm both, and be specific about the action the auditors have to take.'),
    ('The customer project manager asks for a short written summary she can forward to her department heads covering two things: what changes on the day of the Slack to Teams cutover, and what changes on the day of the Egnyte to SharePoint cutover. Both happen the same weekend. Reply to her. Write something she can forward without editing, cover both days, keep it under her department heads patience, and say who to contact for each.'),
    ('A customer asks whether they can migrate their archived Slack channels as archived, so the destination looks exactly like the source. Archived channels cannot be created through the API in any of the twelve supported message combinations, so they arrive as ordinary channels. Their parallel Dropbox to Google copy has no equivalent issue. Reply to them. Explain the limit, propose a naming or permission convention that gets them most of the way, and confirm the content side.'),
    ('The customer sponsor asks why the Amazon WorkDocs to NFS route was quoted so differently from Amazon WorkDocs to SharePoint. The NFS destination supports one-time copy and special character replacement only, with no delta, no versions, no permissions and no timestamps. The SharePoint route supports nearly all of them. Reply to him. Explain what he is actually buying in each case, and ask the question you need answered to recommend one.'),
    ('A customer team asks two questions after their pilot: why messages from a colleague who left the company appear under an administrator name in Teams, and why one Egnyte folder did not copy. The colleague was not mapped between source and destination. The folder name starts with a space, which Egnyte permits and the destination does not. Reply to them. Explain both without jargon, say what you need from them for the first, and confirm what you will do about the second.'),
    ('The customer asks for a written confirmation of scope on two workstreams before the kickoff call: Dropbox to Egnyte for content, and Slack to Teams for messaging. Dropbox to Egnyte carries one-time copy, delta, long path handling, special characters and Dropbox Paper, and nothing else. The Slack side is a full migration. Reply to them. State each scope plainly, flag the gap on the content side before it becomes a surprise, and ask them to confirm in writing.'),
    ('A customer asks whether both of their migrations can be paused halfway if the business needs the weekend back. Channel and direct message migration can be paused and cancelled on every message combination. The ShareFile content copy cannot usefully be paused, because there is no delta to resume with. Reply to them. Answer each honestly, explain what pausing would actually cost on the content side, and offer a safer way to keep the option open.'),
    ('The customer asks two questions before go-live: whether staff will keep their out-of-office replies after the Gmail to Outlook move, and whether external partners keep access to shared Box content after the move to SharePoint. Out-of-office settings do not migrate and each user resets their own. External shares are supported but partners receive a new invitation. Reply to them. Cover both, give a clear instruction for staff, and say what partners will see.'),
    ('A customer wants to understand why their Slack to Teams migration is being split into multiple destination workspaces. Channels above roughly 250,000 messages are split automatically, and three of theirs qualify. In the same email they ask whether the Box to SharePoint copy needs the same treatment; it does not. Reply to them. Explain the split in terms of what their users will see, confirm which three channels, and reassure them about the content side.'),
    ('The customer asks for the status of two workstreams and for one thing to be escalated internally. The Chat to Teams migration is complete. The Dropbox to Google My Drive copy is held up because 6,000 files sit behind a folder path longer than the destination allows and need flattening, which needs their approval. Reply to them. Give the status, explain the flattening in one short paragraph, and ask for the decision in a way that makes it easy to give.'),
    ('A customer sponsor asks whether the reactions on their Google Chat messages will survive the move to Slack, and separately whether the Egnyte to Google My Drive copy will bring the comments left on documents. Reactions are not carried on Chat to Slack. In-line comments are carried on Egnyte to Google My Drive. Reply to him. Get both facts right, do not soften the first, and confirm the second with the confidence it deserves.'),
    ('The customer asks you to explain to their legal team why a date-range search over migrated messages returns different results from the same search in the source. The migration carried the messages, but Teams to Slack posts them live so the searchable timestamp is the migration date, not the original. Their content workstream is unaffected. Reply to them. Explain this carefully enough for a legal reader, say what evidence you can provide of original dates, and confirm the content side.'),
    ('A customer asks two things ahead of their steering committee: whether the Slack to Chat migration will carry their custom emoji, and whether the Box to Google Shared Drive copy will carry Box Notes. Custom emoji are out of scope and arrive as names. Box Notes do migrate, though tables inside them do not survive well. Reply to them. Be clear on both, and give the sponsor one line on each that will survive being repeated in a meeting.'),
    ('The customer wants a firm answer on two dependencies before committing to a date. The Teams to Slack move needs every destination user created first. The NFS to SharePoint copy needs their storage team to lift a read lock. Neither is in your control. Reply to them. Set out both dependencies, say what happens to the date if either slips, and ask them to name an owner for each.'),
    ('A customer asks whether the migration will bring their Outlook Notes and To-Do items into Gmail, and separately whether the Dropbox to Box copy preserves versions. Notes and To-Do are not migrated because Gmail has no equivalent. Dropbox to Box does not carry versions either. Reply to them. Deliver two pieces of unwelcome news in one email without it reading as a list of failures, and offer a practical route for each.'),
    ('The customer project lead asks for confirmation that both workstreams can be validated by their own team before sign-off. The Egnyte to SharePoint side has a validation report generated after every CSV upload. The Slack to Teams side has a pre-scan and a report page with search and pagination. Reply to her. Tell her what she will actually be able to check on each, propose how long validation should take, and offer to walk her team through it.'),
    ('A customer asks two questions about a merger programme: whether the SharePoint Online to Egnyte copy keeps their folder hierarchy, and whether the Slack to Slack move keeps private channels private. The hierarchy is preserved, though names are capped at 200 characters. Private channels stay private, with members added first. Reply to them. Confirm both accurately, flag the name limit before it bites, and say what you need from them about long names.'),
    ('The customer asks you to confirm what the Whiteboard migration covers before they sign. Sticky notes, text, connectors, shapes, images and internal collaborators migrate from Mural and Lucid into Miro. Comments, hand drawing, tables and voting never do, and Lucid additionally loses icons, frames, GIFs and files. Their content workstream is Box to OneDrive and is straightforward. Reply to them. Set the scope out honestly, suggest what they should capture before the move, and confirm the content side.'),
    ('A customer asks why their migration account needs to be added to private channels by the channel owners, when they have given you a full administrator account. Private channel content cannot be read by an administrator who is not a member. Their Dropbox to SharePoint workstream has no such requirement. Reply to them. Explain why the administrator account is not enough, give the owners a simple instruction, and set a date by which you need it done.'),
    ('The customer wants to know whether they can run the delta on their message migration more than once. Unlimited delta is supported on every message combination. They also ask whether their mail migration can do the same; it cannot, and a second mail delta will duplicate calendar events and contacts. Reply to them. Explain the difference between the two workstreams clearly, and give them a rule of thumb for planning the mail cutover around it.'),
    ('A customer asks for a status update covering the Amazon WorkDocs to SharePoint copy and the Chat to Chat tenant move, and asks you to include anything you are worried about. The content copy is on schedule. The Chat move is fine but their users have started pinning messages in the source, which will not carry across because Google Chat has no pinned concept. Reply to them. Give the status, raise the worry before it becomes a complaint, and suggest what to tell users this week.'),
    ('The customer asks two things about the same weekend: whether the Gmail to Gmail move keeps categories and contact labels, and whether the ShareFile to Google My Drive copy keeps external shares. Categories and contact labels do survive Gmail to Gmail. External shares are not carried to Google destinations from ShareFile. Reply to them. Confirm the first, be clear about the second, and say what their external collaborators will need to be sent.'),
    ('A customer asks you to write to their department heads explaining what to expect on Monday after two cutovers over the weekend: Slack to Teams for messaging and Box to OneDrive for content. Reactions will be missing from migrated messages. Content will be complete with permissions intact. Reply on the customer behalf. Write something a department head can read in thirty seconds, tell them the one thing that will generate questions, and give them the helpdesk route.'),
    ('The customer asks whether the migration can start before the statement of work is signed, because their lease ends and they are anxious. Their workstreams are Egnyte to Google Shared Drive and Teams to Teams. Reply to them. Say no clearly and without bureaucratic language, explain what you can do in the meantime that has genuine value, and set out the shortest honest path to a signature and a start date.'),
    ('A customer asks two things after their pilot: why a set of Teams messages appear with an administrator as the sender, and why the Egnyte copy skipped a folder tree that is deeply nested. The senders were not mapped between tenants. The folder tree exceeds the destination path limit and needs flattening. Reply to them. Explain both causes in plain words, say what you need from them for the mapping, and propose the flattening approach for their approval.'),
    ('The customer wants to confirm what happens to users who have left the company. Suspended users are mapped to a service account in the message migration, so their history is preserved under that account. On the content side their Box files need an owner nominated before the copy. Reply to them. Explain both, ask for the nomination in a way that is easy to action, and give them a deadline that protects the schedule.')
    ) AS v(prompt)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-writing-bank-v2');

-- ============================ POOL 2: Escalation Reply (50) ============================
INSERT INTO writing_prompt (created_at, updated_at, category, prompt, level, difficulty)
SELECT now(), now(), 'Escalation Reply', v.prompt, 3, 'HARD'
FROM (VALUES
    ('A customer CIO escalates to your account director. He says the migration lost data: reactions are gone from every migrated Teams channel, and a ShareFile folder created after the copy is not in SharePoint. Reactions are not carried on Slack to Teams and this was in the signed scope. The ShareFile folder is genuinely missing because ShareFile supports no delta and the source was not frozen when it should have been, which is your teams error. Reply to the CIO. Own one, hold the line on the other, and propose a way forward on both.'),
    ('A customer legal counsel writes formally that migrated message timestamps are unreliable and that this may affect a regulatory response. She is right that Teams to Slack posts messages live, so the visible timestamp is the migration date. The original dates exist in the export. Reply to her. Take the concern seriously, explain precisely what is and is not affected, describe what evidence you can produce, and do not minimise it.'),
    ('The customer sponsor has stopped both workstreams and called an emergency meeting. Staff have found that Box Notes migrated into Google Docs with broken tables and missing mentions, and that their Mural boards arrived in Miro without any of the comments. Both were declared out of scope at kickoff, in a document he signed and, he says, was never walked through. Reply to him ahead of the meeting. Do not hide behind the document, address the substance, and propose what happens next.'),
    ('A customer operations director escalates that the migration has cost her team two days of work. Her staff kept working in ShareFile after the freeze date because nobody enforced it, and that work is not in SharePoint. The freeze was communicated once, by email, three weeks earlier. Reply to her. Accept the share of this that is yours, be honest about what cannot be recovered, and set out what you will do to recover what can be.'),
    ('The customer escalates that a supplier received a Teams guest invitation before their procurement notice went out, and that at the same time an external auditor was granted Google Shared Drive access without their approval. The first was a sequencing error by your team. The second was requested in writing by their own compliance officer. Reply to them. Own the first without hedging, evidence the second without appearing to score a point, propose a single approval route for both, and ask them to confirm it.'),
    ('A customer finance director escalates the cost of a change request. A Shared Drive holding eleven terabytes was found during the dry run, in no scoping document, owned by a team that was not at kickoff. He believes it should be absorbed. The statement of work was priced on OneDrive personal storage, where permissions are per user; a shared drive carries group permissions that must be mapped one by one. Reply to him. Hold the position, explain the cost honestly, and offer something real.'),
    ('The customer has written to say they are considering pausing the programme. Their Slack to Existing Teams migration has completed without direct messages, without channel members and without the ability to rename channels, all of which are limits of migrating into an existing tenant, and all of which are in the scope document. Their content workstream is fine. Reply to them. Acknowledge how this feels from their side, be precise about what was agreed, and give them a genuine decision to make.'),
    ('A customer compliance officer escalates that migrated document version dates are all showing as the migration date, and says this makes the records unusable for an audit next month. Google file versions cannot carry their original timestamps and there is no API to change them. The messaging workstream is unaffected. Reply to her. Do not explain the API to a compliance officer as if that settles it, address the audit risk directly, and propose what you can provide.'),
    ('The customer IT manager escalates angrily after being told in a meeting that a second mail delta cannot be run. He had promised it to his own leadership and it is in a board pack. A second delta duplicates calendar events and contacts. His content workstream supports repeated deltas, which is where his expectation came from. Reply to him. Give him a way to correct the board pack that does not humiliate him, and be clear about the constraint.'),
    ('A customer escalates that their engineering runbooks lost their formatting in the migration. They moved Slack to Teams, where formatting stops at bulleted and ordered lists, and code blocks do not survive. They had been told by a colleague of yours that formatting migrates. Reply to them. Correct the record without throwing your colleague under a bus, be accurate about what Slack to Teams does carry, and propose what to do about the runbooks.'),
    ('The customer sponsor escalates that their archived Slack channels came across as ordinary open channels, exposing conversations they had deliberately closed. Archived channels cannot be created through the API in any supported combination. Their Egnyte to SharePoint content workstream is unaffected. Reply to him. Treat the exposure as the real issue rather than the technical one, propose an immediate containment step, and set out the permanent arrangement.'),
    ('A customer escalates that they were advised to buy a Box to Box consolidation by another supplier and that you are now refusing to deliver it. The combination is marked in your documentation as not available in the current code and not to be confirmed with clients. Their second workstream, Outlook to Outlook, is proceeding normally. Reply to them. Explain the position without disparaging the other supplier, offer the supported routes, and keep their trust.'),
    ('The customer escalates that migrated mail has lost their colour categories and that this has broken a filing system three people depend on. Categories are not carried into Gmail because they are not exposed by the Microsoft API. Their NFS to SharePoint content workstream completed cleanly. Reply to them. Recognise the disruption, be exact about the cause, and offer a concrete alternative rather than sympathy alone.'),
    ('A customer director escalates that the migration has damaged their relationship with an external partner, who lost access to a shared library and only found out when a deadline was missed. External shares migrated, but partners must accept a new invitation, and the invitation list was not sent. That was your teams omission. Reply to the director. Apologise once and properly, state what you have already done, and set out how the remaining partners will be handled.'),
    ('The customer escalates that two workstreams they were told were independent have clearly affected each other: the migration account lost access mid-wave and both the Teams to Teams move and the SharePoint copy stopped. They want to know why a single account was used for both. Reply to them. Explain the design decision honestly, say what it cost them, and set out what you are changing before the final wave.'),
    ('A customer escalates after discovering that direct message replies are not in their migrated Teams tenant. Slack to Teams does not migrate DM replies because of an API limitation on the destination. Channel threads did migrate. They say nobody distinguished between the two. Reply to them. Do not argue about what was said, make the distinction clear now, and propose how the DM history can be preserved.'),
    ('The customer escalates the cost of hypercare, which has run to four weeks instead of one across their Gmail to Outlook and Dropbox to SharePoint workstreams. Two of those weeks were driven by label mapping questions from users, which your team had flagged as a training need and the customer chose not to fund. Reply to them. Be fair about the shared responsibility, avoid saying I told you so, and propose how to close hypercare.'),
    ('A customer escalates that a whole department cannot find their files after the Egnyte to OneDrive move, and is talking about a failed migration. The files are there. Folder display is not supported on that destination, so the structure does not render the way it does in Egnyte, and nobody prepared the users. Reply to them. Correct the failed migration framing carefully, explain what they are actually seeing, and get their users unblocked today.'),
    ('The customer escalates that your status reports have said green for three weeks while their staff have been raising problems the whole time. The problems are real but are all documented out-of-scope items on the Slack to Chat and Box to Google workstreams. The reporting did not mention them because they were not defects. Reply to them. Accept that the reporting failed them even though it was accurate, and propose how it changes from this week.'),
    ('A customer escalates that they were not told their Dropbox to Azure Blob archive would contain no permissions, no versions and no timestamps, and are now questioning whether the archive meets their retention obligation. Azure Blob is a data-dump destination and this is documented. Reply to them. Take the retention question seriously rather than defending the scope, set out exactly what the archive holds, and propose how they close the gap.'),
    ('The customer sponsor escalates that a director publicly criticised the programme in a town hall, citing missing message reactions and slow content migration. Reactions are not carried on Teams to Slack. The content slowness was caused by a single folder with a very large number of files being re-enumerated, now fixed. Reply to the sponsor. Give him what he needs to respond publicly, be accurate, and do not sound defensive.'),
    ('A customer escalates that their pilot users have lost confidence and are refusing to move. The issues raised are missing reactions on Teams to Teams, missing pinned messages, and no visible Edited label, all of which are documented limits of that combination. Their content workstream has no complaints. Reply to them. Address the confidence problem rather than the ticket list, and propose something that changes how the next group experiences it.'),
    ('The customer escalates that the migration has generated thousands of sharing emails to their staff over a weekend, and their service desk is overwhelmed. Email notification suppression is not supported on the Amazon WorkDocs to SharePoint combination. Their message workstream did not contribute. Reply to them. Take responsibility for not preparing them, deal with the immediate service desk pressure, and say what you will do before the next wave.'),
    ('A customer escalates that they have discovered a supported feature was disabled on their project without discussion: selective versions were not migrated on their Egnyte content because that destination does not support it. They believe they paid for it. Reply to them. Establish the facts calmly, explain the destination limit, and address the commercial question honestly rather than deferring it.'),
    ('The customer escalates that a regulator has asked for conversations that are no longer retrievable. The Workplace from Meta to Google Chat migration did not carry channel threads or messages from external users, which was documented and accepted. Workplace has since been closed by the customer. Reply to them. This is serious; treat it as such, set out exactly what exists and where, and propose immediate steps rather than an explanation of scope.'),
    ('A customer escalates that your team told them the Slack to Chat move would keep their message links working, and they do not. Message links are supported on Slack to Chat. Something has gone wrong and you do not yet know what. Reply to them. Do not guess at a cause, commit to a specific investigation with a time, and say what you will tell them and when.'),
    ('The customer escalates that they were charged for a change request to add a folder tree that they say was always in scope. The tree sits behind a path longer than the destination allows and required flattening, which is documented as a design decision requiring their approval, not as new scope. Reply to them. Separate the technical work from the commercial question, be willing to be wrong, and propose how you settle it.'),
    ('A customer escalates that their staff are working in two systems six weeks after go-live because the second workstream slipped. The Chat to Teams move completed on time. The ShareFile content copy slipped because their own storage team did not lift a read lock for eleven days. Reply to them. Be factual about the cause without making it an accusation, and focus the reply on how the coexistence period ends.'),
    ('The customer escalates that migrated messages from former employees appear under an administrator name, which their HR director says misrepresents who said what. Unmapped users are posted under the administrator account with a via label. Their content workstream is unaffected. Reply to them. Take the misrepresentation concern seriously, explain what the via label shows, and propose what can be corrected and what cannot.'),
    ('A customer escalates that the go-live was declared complete while 4,000 files were still failing on their names. Your team classified them as an archive nobody uses, based on a conversation with one person. Reply to them. Own the decision and how it was made, do not blame the person who said it, and set out how the 4,000 files will be dealt with and by when.'),
    ('The customer escalates that their board was told the migration would preserve everything, and it has not. The gaps are all documented: no reactions on Slack to Teams, no archived channels anywhere, no second mail delta. The word everything came from a sales conversation. Reply to them. Do not defend the sales conversation, restate what is actually true, and propose how the board is corrected.'),
    ('A customer escalates that two departments have been given different answers about whether their comments will survive the content migration. One is on Egnyte to Google Shared Drive, where in-line comments do migrate. The other is on Egnyte to SharePoint, where they do not. Both answers were correct. Reply to them. Explain why both were right, apologise for how confusing that was, and propose a single source of truth for questions like this.'),
    ('The customer escalates that a senior partner lost a years worth of calendar history in the Outlook to Gmail move. Past events are migrated only for the organiser, so events organised by others are not in his calendar. This is documented. Reply to them. Recognise what this means for a senior person day to day, be precise about what exists where, and propose a practical way to rebuild what matters.'),
    ('A customer escalates that they have lost trust in the reporting because a workstream marked complete turned out to have 200 private channels still sitting in Slack. The channels were never accessible because their owners did not add the migration account, which was requested three times. Reply to them. Accept that complete was the wrong word, be clear about what was asked and when, and propose how the remaining channels get moved.'),
    ('The customer escalates that the Whiteboard migration delivered boards that their design team calls unusable: the comments and votes that recorded their decisions are gone. Comments and voting never migrate to Miro and this was in the scope document. Reply to them. Accept that a technically complete migration can still fail the user, and propose what can be done about the decision record specifically.'),
    ('A customer escalates that their migration has run over budget and they believe the estimate was deliberately low. The overrun is weekend engineering to recover throughput on the content side, approved by them in writing at two in the morning during the cutover. Reply to them. Do not simply point at the approval, explain how the situation arose, and address the estimating concern directly.'),
    ('The customer escalates that a shared mailbox the finance team depends on is accessible to nobody after the Outlook to Outlook move, three days before quarter end. Shared mailboxes migrate but delegates must sign in once, which was in the run book and not in the user notice. Reply to them. Solve the immediate problem first in the reply, then explain, then say what changes about the user communications.'),
    ('A customer escalates that they were advised to decommission their source platforms two weeks after go-live and have now had four recovery requests they cannot serve. Your own advice was a longer overlap; their finance director overruled it to stop licence spend. Reply to them. Do not say you were right, focus entirely on what can be recovered and how, and be clear about what cannot.'),
    ('The customer escalates that migrated content has appeared with sharing links that anyone can open, which their security team says is a breach of policy. The links migrated as they existed in the source, where they were already open to anyone with the URL. Reply to them. Do not treat this as a non-issue because the source was the same, help them contain it today, and propose how the remaining libraries are handled.'),
    ('A customer escalates that their staff cannot tell which migrated Teams messages were edited and are treating the whole history as unreliable. The Edited label is not migrated on Teams to Teams; the latest content of each message is correct. Their content workstream is unaffected. Reply to them. Address the reliability perception rather than the label, and give them something they can tell staff.'),
    ('The customer escalates that a department was migrated without warning and lost a day. The wave plan was agreed with their programme office, who did not pass it to that department. Reply to them. Resist the urge to route the blame to their programme office in the first paragraph, put the affected department first, and propose a change to how waves are confirmed.'),
    ('A customer escalates that their external collaborators are now showing under a user label rather than as external users in the migrated workspace, and their compliance team objects. The label used depends on the combination, and theirs uses the plain user label. Reply to them. Explain what the label does and does not mean about access, take the compliance objection seriously, and propose what evidence you can give them.'),
    ('The customer escalates that they have been asked to freeze their source system for a week and say the business cannot absorb it. The freeze is required because ShareFile supports no delta, so anything created after the copy is not migrated. Their message workstream needs no freeze. Reply to them. Do not simply repeat the requirement, explore what a shorter freeze would cost and risk, and give them options with consequences attached.'),
    ('A customer escalates after their own audit found that the migration account still has access to source systems six weeks after go-live. That is a genuine oversight by your team. Their two workstreams are otherwise closed out. Reply to them. Own it immediately and without qualification, state what has been done since you read their email, and set out how access is governed on the remaining work.'),
    ('The customer escalates that the customer-facing library still carries open sharing links that were supposed to be converted, and that they raised this at go-live. Eighteen thousand links were converted to company-only; the client-facing library was excluded at their request and no owner was assigned to review it. Reply to them. Establish the record gently, accept the follow-up failure, and propose an owner and a date.'),
    ('A customer escalates that they have discovered their Slack to Teams migration split three of their busiest channels across multiple workspaces and their staff cannot find conversations. Channels above roughly 250,000 messages split automatically. This was not explained to users. Reply to them. Explain why the split happened, accept the communication failure, and give them something to send users today.'),
    ('The customer escalates that a project everyone considered finished has produced a data protection question: files belonging to a departed employee were migrated into a colleague personal storage area. An owner was nominated by their own HR team. Reply to them. Do not deflect to the nomination, treat the data protection question as the priority, and set out what you can do to help them assess and remedy it.'),
    ('A customer escalates that they are being asked to pay for a second migration wave that they believe exists only because the first was rushed. The first wave was cut short at their request to meet a lease deadline, which was documented at the time. Reply to them. Acknowledge the pressure they were under, be honest about the consequence, and separate what you would waive from what you would not.'),
    ('The customer escalates that your team has been unresponsive during a live issue: their Chat to Slack migration stopped overnight and nobody answered for six hours. The migration stopped because their own API token was revoked, but the response time is indefensible. Reply to them. Deal with the responsiveness first and fully, explain the cause second, and set out the support arrangement for the rest of the programme.'),
    ('A customer escalates that they have lost confidence in the whole programme after a third change request in six weeks, across their Dropbox to SharePoint and Slack to Teams workstreams. Two were genuine discovery gaps on their side; one was an estimating error on yours. Reply to them. Be scrupulous about which is which, do not bundle them, and propose how the remaining scope gets locked down so there is no fourth.')
    ) AS v(prompt)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-writing-bank-v2');

INSERT INTO seed_state (seed_key) VALUES ('l3-writing-bank-v2') ON CONFLICT DO NOTHING;
