-- =====================================================================
-- Level 3 Writing prompt bank.
--
-- 100 prompts in two pools of 50. WritingService serves one from each pool per attempt, and
-- ContentAssignmentService excludes anything a candidate has already been given, so nobody
-- repeats their own tasks and the pools are large enough that sharing is rare.
--
-- BOTH TASKS ARE CUSTOMER REPLIES. That is the deliberate difference from Levels 1 and 2, where
-- the second task is an internal document -- a status update, an incident report, a Slack
-- message. At this level the candidate writes to the customer twice, because that is the piece
-- of writing that carries commercial risk, and it is the piece a fresher is least ready for.
-- The two pools exist because the selection code splits on the category name, which is how two
-- independent draws are guaranteed; they are not two different kinds of writing.
--   Pool 1, "Customer Email"      -- the routine reply: explaining, confirming, setting a date.
--   Pool 2, "Escalation Reply"    -- the reply written when the customer is unhappy, worried,
--                                   escalating, or asking for something that cannot be given.
--
-- EVERY PROMPT CARRIES TWO MIGRATIONS. The customer raises two things at once -- a Message
-- migration and a Content one, a Mail cutover and a Shared Drive move -- and a reply that
-- answers only the louder of the two is an incomplete answer. That is what makes this Level 3:
-- Levels 1 and 2 give one situation and ask for one reply. The mark for completeness is where
-- this shows up, and the instruction lines in each prompt name both threads on purpose.
--
-- The combinations and their vocabulary come from the migration documentation tool: Message
-- (Slack, Teams and Chat in every supported direction), Mail (Outlook and Gmail, all four), and
-- Content (Shared Drive, SPO and OneDrive, all nine). The scenarios use the real limits of each
-- -- guest accounts issued by the destination, delegates that need one sign-in, labels that are
-- not folders, sharing links that become named members, path length, native-format conversion,
-- version history, delta passes and read-only cutoffs -- so a candidate is writing about work
-- they will actually meet.
--
-- US BUSINESS ENGLISH throughout, since these customers are American: kickoff, statement of
-- work, change request, punch list, hypercare, go-live, cutover window, sign-off, escalation
-- path, service level agreement, root cause analysis. Figures group in threes with commas and
-- amounts are in dollars.
--
-- Avoid apostrophes: these are single-quoted SQL literals.
-- =====================================================================

-- ---------- Customer Email, part 1 of 2 ----------
INSERT INTO writing_prompt (created_at, updated_at, category, prompt, level, difficulty)
SELECT now(), now(), 'Customer Email', v.prompt, 3, 'HARD'
FROM (VALUES
    ('Priya, an IT manager at TechNova, writes on Monday morning with two problems. Her staff say roughly 200 Slack channels are missing in Teams, and separately her finance team cannot open files that were shared with them by link before the Shared Drive to SPO move. The channels are private ones whose owners never added your migration account, and they are still in Slack. The links became company-only shares by design, and the finance team simply needs to open them from the new library. Reply to Priya. Deal with both, explain each in plain words, say who has to act on each, and give a date for the channels.'),
    ('A customer sponsor emails asking why his Gmail to Outlook cutover finished on time while the OneDrive tenant-to-tenant move is now four days late, when both were quoted for the same weekend. The mail side was straightforward. The content side ran long because 11,000 files breached the path-length limit at the destination and had to be flattened one folder level. Reply to him. Explain why the two differ without technical jargon, give the new finish date, say what is being done now, and confirm the mail side needs nothing further.'),
    ('A customer operations lead reports that shift handovers posted as threaded replies in Chat have arrived in Teams as one flat post, and in the same email asks when her department SPO libraries will be visible. The handover problem is real and affects 11 spaces, which will be re-migrated on Thursday. Her libraries migrated on Saturday and are visible under a new site name she has not been told about. Reply to her. Own the handover fault, give the fix date, tell her where the libraries are, and apologise once.'),
    ('The programme manager at a customer asks two things in one message: whether the 40 supplier guest accounts in the Teams tenant move have been re-invited yet, and whether the delta pass on the Shared Drive workstream has run. The guests are being invited in waves and 26 of 40 have accepted. The delta ran overnight and cleared 1,900 changed files. Reply to him. Give both numbers plainly, say what remains on each, name what you need from his procurement team, and set the next update.'),
    ('A customer finance director writes that his team has lost their email rules after the Outlook to Gmail move and, in the same email, that a shared drive he expected to see is not there. Rules do not migrate and each user rebuilds their own; there is a published recipe for the twenty most common. The shared drive is out of scope in the signed statement of work and would be a change request. Reply to him. Be clear about both, avoid sounding defensive about either, offer the recipe, and set out what a change request would involve.'),
    ('A customer IT director asks for a status on two workstreams before her board meeting tomorrow: the Slack to Chat migration and the SPO to SPO tenant consolidation. Slack to Chat is complete for 900 users with formatting loss on runbooks, which was declared out of scope at kickoff. The SPO consolidation is 60 percent done and on schedule to finish Friday. Reply to her. Give each in two lines, be honest about the formatting loss, state what she can tell her board, and offer to join the call.'),
    ('A customer writes to say his users are confused because both the old and the new systems still work: they can still post in Slack and still open files in the old shared drive. The overlap is deliberate. Slack goes read-only in six days and the source drive is decommissioned 30 days after go-live, on a date he signed. Reply to him. Explain why both are still live, give both dates, say what staff should use meanwhile, and offer a short notice he can circulate.'),
    ('A customer compliance officer asks two questions. Will an e-discovery search on migrated Chat messages return the same results as before, and did the claims library keep its version history through the SPO to Shared Drive move? Timestamps are preserved exactly, though the attribution shows as posted-as. Version history was kept, which is why that workstream ran three weeks longer. Reply to her. Answer both directly, explain the posted-as attribution once, and offer evidence she can put in front of her regulator.'),
    ('A customer HR director emails about two things she considers urgent: 14 leavers whose Shared Drive content now appears to belong to nobody, and a shared mailbox in the Gmail to Outlook move whose delegates cannot access it. The leaver content is on an orphan drive owned by an IT service account, awaiting her decision. The delegates each need to sign in once. Reply to her. Explain both, tell her exactly what decision you need and by when, and give the delegates instruction in one line she can forward.'),
    ('A customer project manager writes that his engineering team is unhappy that formatted runbooks arrived as plain text in Chat, and asks in the same email whether the OneDrive to SPO move will do anything similar to their design files. The formatting loss was declared out of scope at kickoff. Design files move without conversion because they are not Google native formats. Reply to him. Address the runbooks honestly, reassure him about the design files with a reason, and offer one practical option for the runbooks.'),
    ('A customer sponsor asks why she is being asked to nominate 41 named people for external access when, before the migration, sharing was simply a link. The Shared Drive destination grants access by account rather than by link, so each external person must be added individually. She also asks when her Slack to Teams private channels will finish; 290 of 400 owners have acted. Reply to her. Explain the sharing change without blaming the platform, give the private channel position, and name the two things you need from her.'),
    ('A customer writes at nine in the evening: a director cannot find last year contracts after the SPO to OneDrive move, and separately says half his team is still receiving mail in the old Gmail account. The contracts are in an archive folder under a new parent. The mail is arriving in the old account because two partner domains are still caching the old record, which clears within 72 hours. Reply to him tonight. Reassure on both, say exactly where the contracts are, give the mail clearing time, and say what you will confirm tomorrow.'),
    ('A customer asks for two things in one email: confirmation that nothing was deleted during the Teams to Teams consolidation, and an explanation of why the file count in the SPO report is 406 lower than his own count. Nothing was deleted; the source is intact. The 406 are duplicate files merged by the destination on arrival, which is documented behaviour. Reply to him. Give the assurance plainly, explain the merge without being technical, offer the evidence for both, and say who signs the confirmation.'),
    ('A customer training lead asks whether her staff need to do anything before Friday for either of the two migrations running that weekend: Slack to Teams and OneDrive to SPO. For Slack, private channel owners must add the migration account. For OneDrive, anything genuinely personal should be moved out before the team libraries are created. Reply to her. Give the two actions as plain instructions, say who each applies to, give the deadline, and offer a one-page notice she can send.'),
    ('A customer asks why the same weekend included a completed Chat to Teams migration and a Shared Drive move that only reached 60 percent. The Message side had almost no group direct messages, which are the slowest objects. The Content side lost four hours to a single flat folder holding 220,000 files, which was excluded and pre-staged separately. Reply to him. Explain both outcomes in terms he can repeat to his own leadership, give the revised completion date, and confirm nothing was lost.'),
    ('A customer legal team asks two questions before sign-off: whether the 9,000 messages under legal hold were migrated with the rest of the Chat consolidation, and whether the SPO libraries retained their retention labels. The held messages were deliberately left in the source tenant, which stays licensed. Labels migrated but the rules behind them were rebuilt first, which added five weeks. Reply to them. Answer both precisely, explain why one was left behind on purpose, and state what evidence you can provide.'),
    ('A customer emails to say that a folder they deleted before the Shared Drive to OneDrive migration has reappeared, and that a Slack channel they archived is now active again in Teams. Both were restored from the source during the copy, which is expected when items are removed shortly before a migration. Reply to them. Explain how both came back, confirm it is safe to remove them again, describe how to avoid it in the next wave, and offer to check for other cases.'),
    ('A customer asks for a single date on which she can tell her staff the migration is finished, when in fact two workstreams finish on different days: Gmail to Outlook completes on the 14th and the SPO to SPO consolidation on the 21st, with hypercare running two weeks past each. Reply to her. Give both dates clearly, propose the single date she should communicate and explain why, describe what hypercare means for her staff, and offer wording she can use.'),
    ('A customer asks whether the migration can be reversed if the business rejects it, having heard from a colleague that the old Slack workspace is already gone. The Slack workspace is read-only, not deleted, until day 30. The Shared Drive source is untouched and stays so until his written sign-off. Reply to him. Correct the misunderstanding without embarrassing his colleague, describe the safety net on both workstreams, give the dates each ends, and name the decision he has to make.'),
    ('A customer emails asking why 30 of his private Slack channels were never migrated and why 2,000 folders still carry a rename request from his project leads. The 30 channels had owners who never added the migration account despite two weeks of chasing. The folders exceed the destination path length and cannot be truncated because their names are project codes. Reply to him. Set out both without blaming his staff, give the options for each, state the cost of the read-only Slack licence, and ask for a decision.'),
    ('A customer asks two questions after go-live: why their meeting recordings are not in the Teams channels where they used to be, and why some SharePoint sites have a marker in their names. Recordings live in the site behind a channel and were exported to a folder his team owns. The markers are temporary and come off at sign-off, so that nobody works in the wrong copy. Reply to him. Explain both, say where the recordings are, tell him when the markers disappear, and confirm nothing is missing.'),
    ('A customer sponsor writes that her CFO wants the old estate switched off immediately to stop the licence spend, while her IT manager wants 30 days. Across your previous projects the last genuine recovery request averages day 19, but two thirds could have been served from the destination. Reply to her. Present the evidence honestly including the part that weakens the 30-day case, propose a middle option with a cold export, give its cost, and ask for a decision date.'),
    ('A customer asks why their Outlook to Gmail migration has produced roughly 340 duplicate calendar entries and, in the same message, whether their Shared Drive permissions survived. Duplicates come from open-ended recurring series with a moved occurrence, affecting about four percent of series, and are cleared during hypercare. Drive permissions were mapped group by group and verified after cutover. Reply to them. Explain the duplicates without minimising, give the clearing plan, confirm the permissions with the evidence, and set a follow-up date.'),
    ('A customer asks for help explaining to their staff why messages in Teams show a posted-as attribution and why files in SPO show a migration service account as the last editor. Both are normal artefacts of migration and neither changes the content or the original timestamps. Reply to them. Explain both in language a non-technical employee will accept, say what has not changed, offer a short notice for staff, and give a contact for anyone still concerned.'),
    ('A customer emails on the Monday after go-live: their helpdesk has taken 90 calls about mail and 40 about files. The mail calls are people whose out-of-office and rules did not migrate, which was communicated. The file calls are external sharing links that now require named accounts. Reply to them. Acknowledge the volume, separate the two causes, give the self-service answer for each, and propose one thing that would reduce the calls this week.')
    ) AS v(prompt)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-writing-bank-v1');

-- ---------- Customer Email, part 2 of 2 ----------
INSERT INTO writing_prompt (created_at, updated_at, category, prompt, level, difficulty)
SELECT now(), now(), 'Customer Email', v.prompt, 3, 'HARD'
FROM (VALUES
    ('A customer records manager asks how a resident freedom-of-information request will be answered now that two authorities filing conventions have been merged into one SPO structure, and separately what happened to chat older than 18 months from the authority that deleted it. The structure she signed means one search rather than two. Eleven of the eighteen months were backfilled from the other authority archive; seven months are gone. Reply to her. Answer both, be exact about the seven-month gap, explain how it is documented, and confirm the search improvement.'),
    ('A customer asks two related questions before signing the statement of work: whether their Gmail archive is included in the mail migration, and whether version history is included in the OneDrive move. The archive is a separate export and adds four days, currently out of scope. Version history is included and is the reason the content estimate is higher than they expected. Reply to them. Answer both, make clear which costs more and why, offer the change request for the archive, and ask for a decision date.'),
    ('A customer emails to say that two departments have reported opposite problems: sales cannot see the files they expect in SPO, and marketing can see files they believe should be restricted. Sales files are in a library with a new name they were not told. Marketing is seeing content whose permissions were mapped from a Shared Drive group that included people who left. Reply to them. Treat the second as the more serious, explain both, say what is being fixed and when, and name what you need from their HR list.'),
    ('A customer asks for confirmation that the Slack to Teams and OneDrive to SPO migrations are complete so they can release the final payment, but two punch-list items remain: 41 app integrations to retire or rebuild, and 2,000 folders awaiting rename. Reply to them. Confirm what is genuinely complete, be straight about the two open items with owners and dates, explain why they do not block closure, and set out what the final payment is being released against.'),
    ('A customer department head writes that she was not consulted before her Chat spaces were mapped into Teams channels, and separately that her team library has fewer documents than she counted. The mapping followed the structure her IT director signed. The count difference is duplicate files merged on arrival. Reply to her. Take the consultation point seriously without undermining her IT director, explain the count, offer to walk her folder structure with her, and give a date.'),
    ('A customer asks whether the migration will affect an integration between their SharePoint library and their finance system, and whether their Teams bots will keep working after the tenant move. The SharePoint integration must be reconnected and tested end to end. The bots are tenant-scoped and have to be re-installed in the destination. Reply to them. Explain both plainly, say who reconnects each, give the downtime expected for the finance integration, and ask them to schedule it.'),
    ('A customer emails that their staff are receiving guest invitations from your team that look like phishing, and separately that two shared drives are still read-only three days after go-live. The invitations are genuine and should have been preceded by a procurement notice. The drives are read-only pending their own owner confirmation. Reply to them. Apologise once for the invitation sequence, tell them how to verify an invitation is genuine, explain the read-only drives, and give the action that releases them.'),
    ('A customer asks why the Teams to Chat migration left 900 one-to-one conversations behind while the SPO content moved in full. The rule agreed with their legal team was that a one-to-one chat migrates only where both participants transfer with the division. Content had no such ambiguity. Reply to them. Restate the rule and where it was agreed, explain why content was different, say where the 900 conversations remain, and offer the evidence for the sale documentation.'),
    ('A customer IT manager asks for the migration to pause for two weeks during an audit, with both workstreams in flight: Gmail to Outlook is mid-wave and the Shared Drive copy is 70 percent done. Pausing is safe but the source and destination drift while stopped, and a catch-up pass is needed on restart. Reply to him. Agree to the pause, explain the drift in simple words for each workstream, describe the catch-up, and confirm the restart date and what it costs.'),
    ('A customer asks two things after reading your weekly report: why the item count in the Content workstream fell by 400,000 overnight, and why the Message workstream shows no progress for three days. The count fell because a reporting error that double-counted files in shared folders was corrected. The Message workstream was waiting on private channel owners. Reply to them. Own the reporting error first, explain the correction, give the true position on both, and say what has changed so it does not recur.'),
    ('A customer asks whether they can keep their old Slack workspace and their old Shared Drive for a year rather than 30 days, for peace of mind. Both are possible at a licence cost, and the evidence says almost every genuine recovery request arrives inside 19 days. Reply to them. Give the honest evidence including where it favours their instinct, state the annual cost of each, propose the cold-export alternative with its price, and ask which they want.'),
    ('A customer procurement lead writes that an invoice includes 19,000 dollars of weekend engineering they did not expect, and in the same email that a Chat space they need is missing. The engineering was approved in writing at two in the morning by their own project manager. The missing space had more than 20 participants and became a channel. Reply to them. Handle the invoice factually without sounding defensive, offer the approval evidence, explain the space conversion, and tell them where to find it.'),
    ('A customer asks for a plain-English explanation they can send to 1,400 staff covering what changes on Monday across both migrations: Chat becomes Teams and personal SPO folders become OneDrive. Reply to them with the email they can forward. Explain what staff will see on Monday for each, name the two actions staff must take, say what has not changed, and give one place to get help.'),
    ('A customer emails that their external auditors have lost access to a SharePoint site and their supplier has lost access to a Teams channel, both after the tenant consolidation. External identities are issued by the destination tenant and must be re-invited in both cases. Reply to them. Explain the common cause once, give the specific step for each, say how long each takes, and ask for the two lists of named individuals.'),
    ('A customer asks why you are recommending a pilot of 80 users drawn from their largest department rather than the 40-person department they suggested, for a migration that spans both Teams and OneDrive. The small department uses almost no shared folders and no external sharing, so it proves little about the rest. Reply to them. Make the case in two sentences, name what the pilot will measure on each workstream, propose dates, and ask them to nominate members.'),
    ('A customer asks for the two migrations to be brought forward by a week because of an office move, when one depends on their own account clean-up and the other on their project leads renaming folders. Reply to them. Say yes in principle, name the two dependencies plainly, give the dates each is needed by, and describe exactly what happens to each workstream if either slips.'),
    ('A customer emails that their CEO has asked why the company is moving mail to Google while moving files to Microsoft, and wants something he can say. Both directions follow separate business decisions taken by different parts of their organisation. Reply to them. Give a short, confident explanation the CEO can repeat, avoid criticising either decision, state what your team is doing to keep both consistent for users, and offer to brief him directly.'),
    ('A customer writes that a document approved last week now shows an older version as current in SPO, and that a pinned message in Teams has disappeared. The document was overwritten by a delta pass carrying forward a source edit. The pinned message survived but pins do not always carry, and it is still in the channel history. Reply to them. Explain both, say how to restore the approved version, tell them where the message is, and describe the control that stops the first recurring.'),
    ('A customer asks two questions about cost: why the Content workstream came in 19,000 dollars over while the Message workstream came in 11,000 under, and whether the difference can be offset. The overrun was weekend engineering they approved; the underspend was a wave that finished early. Reply to them. Explain both figures, be clear about what was approved and by whom, say plainly whether an offset is possible, and name who can decide it.'),
    ('A customer asks for evidence that no employee content left the European region during either migration, having heard that progress reports are generated in North America. The content paths were European throughout. The reporting service was North American and was moved to a European instance before go-live, at a cost of three weeks. Reply to them. Answer the content question directly, disclose the reporting position without being asked twice, explain what was changed, and offer the document that evidences both.'),
    ('A customer asks when their staff can start using the new Teams channels and the new SPO libraries, having been told different dates by two of your colleagues. Channels are available now; libraries open after their own sign-off, which is outstanding. Reply to them. Take ownership of the inconsistency, state the correct position for each, say what is needed to open the libraries and from whom, and confirm you are now the single point of contact.'),
    ('A customer emails at the end of the project to thank the team and asks two final questions: what happens to their data on your systems, and who they contact after hypercare ends. Nothing is retained beyond the reports. Support moves to a named team with a four-hour response rather than one hour. Reply to them. Thank them specifically, answer both questions precisely, set the support expectation clearly, and confirm the closure date.'),
    ('A customer asks whether the 2.1 million documents that arrived with retention labels are genuinely classified, having heard that labels can migrate without their rules. In their case the rules were rebuilt before migration, which is why the workstream ran five weeks longer. Their Chat messages under hold were left in the source. Reply to them. Confirm the classification is real and say how it can be verified, explain the five weeks as the reason it is real, and restate the position on the held messages.'),
    ('A customer asks two things before their board meeting: how many of their 400 private Slack channels are now in Teams, and how much of their 60 terabytes has landed in OneDrive. The figures are 370 of 400 channels and 58 of 60 terabytes, with the remainder blocked on owner actions in both cases. Reply to them. Give both figures, explain the same underlying blocker for each, name what the board can do about it, and offer a one-slide summary.'),
    ('A customer writes that their staff are using a personal cloud account to move files between home and work because they believe the new SPO libraries block external access, and separately that nobody can find the Teams channel for a project that was renamed. The belief is wrong; controlled external sharing is available. The channel was renamed at their own request. Reply to them. Correct the belief without implying misconduct, give the approved way to share externally, tell them the new channel name, and offer a short briefing.')
    ) AS v(prompt)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-writing-bank-v1');

-- ---------- Escalation Reply, part 1 of 2 ----------
INSERT INTO writing_prompt (created_at, updated_at, category, prompt, level, difficulty)
SELECT now(), now(), 'Escalation Reply', v.prompt, 3, 'HARD'
FROM (VALUES
    ('A customer CIO has emailed your director, copying you, saying the programme is out of control: the Slack to Teams migration has left 30 private channels behind and the Shared Drive move is four days late. The channels were blocked because their owners never added the migration account despite two weeks of chasing. The four days were lost to 11,000 path-length breaches that were found in the dry run and reported at the time. Reply to the CIO directly. Do not blame his staff, state the facts of each with dates, say what you are doing now, and propose one change to how this is escalated in future.'),
    ('A customer sponsor writes that she has lost confidence after being told two different completion dates for the Gmail to Outlook cutover and a third for the OneDrive move. All three dates were given by different people on your side and two of them were wrong. Reply to her. Apologise once and plainly, give the single correct date for each workstream, explain what caused the inconsistency, and state what you have changed so that one person now owns the dates.'),
    ('A customer legal counsel writes that migrated Teams messages show a posted-as attribution and asks whether the company can still rely on them as evidence, while also questioning whether the SPO version history is admissible. Timestamps are preserved exactly and the original author is recorded; version history is complete. Reply to counsel. Answer the evidential question carefully and without overpromising, explain the attribution once, describe the evidence you can supply for both, and offer a call with your own compliance lead.'),
    ('A customer demands a refund because their Chat to Teams migration overran by one day, when the overrun was caused by their own account clean-up arriving nine days late, which you can evidence, and the parallel SPO workstream finished early. Reply to them. Stay professional and do not concede fault, set out the sequence factually, acknowledge their frustration, note the early finish without scoring a point, and offer a goodwill gesture that is not a refund.'),
    ('A customer head of security has escalated because your migration service account was granted an exemption from their conditional access policy, and separately because 41 external people were added to a Shared Drive by account. Both were requested and approved by his own team in writing. Reply to him. Do not sound defensive, reference the approvals without appearing to hide behind them, explain why each was necessary, and propose a joint review of both before the next wave.'),
    ('A customer operations director writes that his stores lost their shift handovers when Chat spaces became Teams channels, and that the same weekend his files moved somewhere nobody can find. The handover threading fault is genuine and affects 11 spaces. The files are in a renamed library that was communicated only to IT. Reply to him. Take responsibility for both, give the re-migration date for the handovers, tell him exactly where the files are, and say what you are changing about how store staff are told.'),
    ('A customer programme director threatens to stop the second phase because the first produced a punch list of 41 app integrations and 2,000 folder renames, which she says should have been foreseen. Both were declared at kickoff and are in the signed scope document. Reply to her. Acknowledge the frustration without accepting a charge that is untrue, point to where each was agreed in a way that does not read as an accusation, propose how phase two avoids the same feeling, and ask for a call.'),
    ('A customer finance director escalates that he is being asked to pay for weekend engineering on the Content workstream while the Message workstream finished under budget, and calls the billing inconsistent. Both are true and both were approved separately. Reply to him. Explain each figure, be transparent about what was approved and by whom, address the fairness point directly rather than deflecting it, and offer to walk both invoices line by line.'),
    ('A customer works council representative writes formally, objecting that employee file names and mailbox display names left the European region in migration reports, even though the content did not. This is accurate; the reporting service was North American and has since moved. Reply formally. Confirm what happened without minimising it, distinguish content from reporting precisely, describe the remediation and its date, and offer the evidence pack the council will need.'),
    ('A customer IT manager escalates that two of his staff spent a weekend renaming folders that your team said could not be truncated, and calls it work that should have been included. The names are project codes and truncation would have made drawings unfindable, which was explained at the dry run. Reply to him. Recognise the effort his staff put in, explain why truncation was refused in terms of what it protected, say what you could have done differently, and offer help for the remaining files.'),
    ('A customer CEO office writes asking why staff received guest invitations that their own security awareness training told them to report, during a Teams tenant move, and why the same week a supplier lost access to a SharePoint site. Both are the same root cause: external identities are issued by the destination tenant. The procurement notice that should have preceded the invitations was not sent. Reply to the CEO office. Explain the cause once in non-technical language, own the missing notice, describe the corrected sequence, and confirm the supplier position.'),
    ('A customer escalates that their e-discovery search on migrated Chat now returns different results from the same search run before the migration, which they say breaches a commitment. The difference is that 9,000 messages under legal hold were deliberately left in the source tenant, which was agreed with their compliance officer. Reply to them. Take the concern seriously, explain the deliberate exclusion and where it was agreed, describe how a complete search is run across both, and offer to document it for their regulator.'),
    ('A customer department head has escalated to her director that she was never consulted about the Teams channel structure or the SPO library naming, both of which were signed off by her IT director. Reply to her, copying nobody. Do not undermine her IT director, acknowledge that a sign-off is not the same as being consulted, explain what can still be changed on each and what cannot, and propose a working session with a date.'),
    ('A customer escalates after discovering that a document approved last week now shows an older version in SPO and that a Teams message they relied on cannot be found. The document was overwritten by a delta pass carrying forward a source edit; it is recoverable. The message is in the channel history but no longer pinned. Reply to them. Treat the document as the serious item, explain both, give the recovery steps and times, and describe the control being added.'),
    ('A customer sponsor writes that their board has asked why the programme reported 400,000 more items than actually exist, and calls the reporting untrustworthy. A double-count of files in shared folders was corrected in one step, and the Message workstream figures were never affected. Reply to the sponsor. Lead with the corrected number rather than the explanation, state what the board decision should now be based on, explain the cause briefly, and say what has changed in the report.'),
    ('A customer escalates that two of your engineers gave contradictory advice about whether Outlook rules migrate to Gmail and about whether Shared Drive version history is preserved. One answer was right in each case. Reply to them. Give the correct position on both without publicly correcting either engineer, explain how the confusion arose, say who they should ask in future, and offer a written summary they can circulate.'),
    ('A customer procurement director escalates that the statement of work covered a Shared Drive that turned out to need a change request of 48,000 dollars, and that in the same programme a Slack formatting loss was called out of scope. He says the scope was written to your advantage. Reply to him. Address the accusation directly and calmly, explain how each item was priced and where it is recorded, offer an independent review of the scope document, and propose how phase two is scoped differently.'),
    ('A customer escalates that hypercare is ending while 340 duplicate calendar entries and 30 unmigrated Slack channels remain open. Both are known, both have owners, and neither requires hypercare to resolve. Reply to them. Explain what hypercare is for and what it is not, give the owner and date for each open item, offer to extend cover for one of the two if they choose, and ask which.'),
    ('A customer CIO writes that his staff are still using the old Slack workspace and the old Shared Drive three weeks after go-live and blames a lack of communication. Both remain deliberately read-only until day 30, which was communicated to his IT team but not to end users. Reply to the CIO. Accept the communication gap, distinguish what was decided from what was announced, give the decommission dates, and offer wording that goes to all staff rather than to IT.'),
    ('A customer escalates after an auditor found documents in SPO that appear classified but behave as though they are not, in a programme where their Chat migration also carried retention obligations. In their case the retention rules were rebuilt before migration and the labels are genuine. Reply to them. Answer the auditor concern with evidence, explain how a decorative label would have looked different, restate the five-week decision that protected them, and offer a joint session with the auditor.'),
    ('A customer sponsor demands that the old estate be switched off tomorrow to stop licence spend, against your advice to keep 30 days, in a programme covering both a Teams consolidation and a Shared Drive move. Reply to her. Give the evidence honestly including the part that supports her position, state your recommendation clearly once, propose a cold-export compromise with its cost, and confirm you will follow her decision either way.'),
    ('A customer escalates that migrated files show a migration service account as the last editor and migrated messages show a posted-as attribution, and says the audit trail has been destroyed. Neither is true: original authors and timestamps are preserved. Reply to them. Correct the misunderstanding respectfully, explain what each artefact is and what it is not, describe how the original author can be seen on both, and offer a demonstration.'),
    ('A customer head of HR escalates that content belonging to 14 leavers is now on an orphan drive with no owner, and that a shared mailbox has been inaccessible for a week. The orphan drive awaits her own decision, requested twice. The mailbox needs each delegate to sign in once, which was in the run book but not the user notice. Reply to her. Own the notice gap, give the mailbox fix in one line she can forward, restate the decision you need on the drive with a deadline, and offer to prepare the options.'),
    ('A customer escalates that the Chat to Teams migration finished early while the Shared Drive move slipped, and asks why the fast team could not help the slow one. The two require different skills and the slow workstream was blocked on customer folder renames rather than on effort. Reply to them. Answer the question rather than dismissing it, explain the blocker without blaming their staff, say what your team did with the freed capacity, and give the revised date.'),
    ('A customer escalates on behalf of an engineering team that has lost formatted runbooks in the Slack to Chat move and now discovers that Google-native conversion has also stripped comments from design documents. The formatting loss was declared out of scope; the comment loss on conversion was in the design and should have been flagged more loudly. Reply to them. Distinguish the two honestly, accept the second as a communication failure, propose a recovery option for each, and give dates.')
    ) AS v(prompt)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-writing-bank-v1');

-- ---------- Escalation Reply, part 2 of 2 ----------
INSERT INTO writing_prompt (created_at, updated_at, category, prompt, level, difficulty)
SELECT now(), now(), 'Escalation Reply', v.prompt, 3, 'HARD'
FROM (VALUES
    ('A customer escalates that a report you sent contained the name of another customer, in a week when they are already unhappy about a four-day slip on their SPO workstream. Both are your side. Reply to them. Apologise for the disclosure without minimising it, ask them to delete the file, say what has been done internally within the hour, then address the slip separately with its new date rather than letting one issue hide the other.'),
    ('A customer escalates that their migration was paused for eleven hours by a security policy that blocked your service account, and then nine days later the same thing stopped their second workstream. Both are true. The first was a discovery gap and the second was a remediation gap, since the exemption was raised for one account rather than the class. Reply to them. Separate the two causes honestly, do not present the second as bad luck, state both changes made, and ask for the class-level exemption.'),
    ('A customer director escalates that his team was told a Teams to Chat migration would be seamless and now finds code blocks arriving as plain text and one-to-one chats missing. The formatting was declared out of scope; the missing chats follow a rule his own legal team agreed. Reply to him. Address the word seamless directly and fairly, restate where each was agreed without hiding behind paperwork, offer a practical option for the runbooks, and confirm where the excluded chats remain.'),
    ('A customer escalates that 26 of 40 suppliers have accepted Teams guest invitations and the remaining 14 are refusing because their own security teams flagged them, while in parallel 41 external people still cannot reach a Shared Drive. Reply to them. Explain the single common cause, propose a joint communication signed by their procurement team, give a realistic timeline for both groups, and say what you need from them today.'),
    ('A customer sponsor escalates that the programme has consumed almost all its contingency by week twelve and blames the migration team, when in fact three customer-side delays account for most of it. Reply to the sponsor. Report the remaining contingency as a single figure, set out the three delays factually and without accusation, state what a further delay costs, and ask for the specific decisions you need to protect the date.'),
    ('A customer escalates after their CFO discovered the old Slack workspace is still licensed at 11,000 dollars a month and the old Shared Drive at a further 4,000, three weeks after go-live. Both were agreed as a 30-day safety net. Reply to them. Confirm the costs precisely, restate what the overlap buys with the evidence behind it, offer to end it early with the risk stated plainly, and ask for a decision within two days.'),
    ('A customer escalates that an engineer on your team was abrupt on a call about their Gmail to Outlook cutover, and separately that a promised file report never arrived. The engineer had been asked the same question by four people in two days. The report was genuinely late. Reply to them. Apologise for the experience without conceding that your engineer misbehaved, address the report as the concrete failure it is, propose a single point of contact, and give the report date.'),
    ('A customer escalates that their staff have twice been asked to rename folders and re-confirm channel owners, and say the migration team is offloading its work onto them. Neither task can be done by your team: folder names encode project codes and channel ownership is a permission only the owner can grant. Reply to them. Take the frustration seriously, explain plainly why each has to be theirs, describe what you have automated around it, and offer to run drop-in sessions.'),
    ('A customer legal team escalates that 900 one-to-one conversations were left behind in a divestiture and asks who authorised it, while also querying whether 406 documents were lost. The conversation rule was agreed on a call with their own counsel; the 406 are merged duplicates. Reply to them. Answer the authorisation question directly with the date and participants, explain the merge with evidence, and propose that both be written into the sale documentation.'),
    ('A customer escalates that their regulator has asked for evidence of the migration and they do not know what to send, having received an item-count reconciliation for content and nothing at all for messages. Reply to them. Explain what evidence exists for each workstream, be honest that message evidence takes a different form, offer to prepare a single pack, and give the date it can be with them.'),
    ('A customer IT director escalates that a department head went directly to your engineer and had a channel structure changed without his approval, in a programme where a similar informal request also altered a SPO library name. Reply to the director. Accept that both should have come through him, describe how each request will be handled from now on, avoid criticising the department head, and confirm what has already been changed.'),
    ('A customer escalates that hypercare tickets are being answered in four hours when they were promised one, on both the Teams and OneDrive workstreams. The one-hour response applied during hypercare, which ended last week, and this was stated at handover but not repeated to end users. Reply to them. Explain the change without sounding as though you are quoting a contract, take responsibility for the communication gap, offer a short extension on one workstream if it helps, and confirm the support route.'),
    ('A customer escalates that they cannot tell whether they are working in the source or the destination SharePoint site, and that staff are still posting in the old Slack workspace. Both are consequences of running estates side by side. Reply to them. Explain why the overlap exists, describe the temporary site markers and their removal date, give the Slack read-only date, and propose one immediate change that reduces the confusion this week.'),
    ('A customer escalates after an internal audit found that permissions on a migrated SPO library include people who left the company, and separately that a Teams channel is accessible to a supplier who should have been removed. Both came from source groups that were never cleaned up. Reply to them. State plainly that both are real, explain the common source, say what has been remediated already, and ask for the HR leaver list that closes it properly.'),
    ('A customer escalates that the programme has produced two migrations that finished on different dates, leaving staff using a mixture of old and new systems for two weeks, and calls it poor planning. The gap was deliberate, to keep the helpdesk from facing both at once. Reply to them. Explain the reasoning without dismissing the complaint, acknowledge the cost to users, describe what you did to reduce it, and offer to compress the gap in the next phase.'),
    ('A customer sponsor escalates that they have received an invoice for a change request they say was never approved, covering a Shared Drive that was out of scope, in the same month that their Chat migration finished early. Reply to them. Ask for nothing until you have stated the facts, reference the approval and offer to forward it, avoid using the early finish as leverage, and give a named contact in your finance team.'),
    ('A customer escalates that migrated mail is missing folders, and separately that their document library shows fewer files than the source. The mail folders became labels and are visible under a different view. The library difference is merged duplicates. Reply to them. Take both seriously rather than explaining them away, give the one step that shows each is intact, offer a working session, and say what you will verify before that session.'),
    ('A customer escalates that their staff were told to reset out-of-office replies and rebuild rules after the Gmail to Outlook move, and that the same week their OneDrive external links stopped working, and asks why so much was left to users. Reply to them. Explain what genuinely cannot be migrated and why, distinguish that from the link change, which was a security decision their own team requested, and propose help for the users most affected.'),
    ('A customer escalates that a wave was run without their sign-off on the Teams side while the SPO wave correctly waited for theirs. The Teams wave was authorised verbally on a call by their project manager. Reply to them. Do not contradict their account outright, state what was said and by whom with the date, accept that verbal authorisation was not good enough, and propose a written gate for every remaining wave.'),
    ('A customer escalates that they were promised the migration would be invisible to end users, and both workstreams have produced visible change: a posted-as attribution in Teams and a new library name in SPO. Reply to them. Address the promise honestly, explain what each artefact is and why it cannot be avoided, say what you can still change and what you cannot, and offer a communication that turns both into something staff understand rather than distrust.'),
    ('A customer escalates that their pilot group signed off a Chat to Teams migration that then failed for store staff, while the parallel content pilot was representative and succeeded. Reply to them. Accept the pilot design fault as yours, explain precisely what the pilot did not cover, describe the re-migration for the affected spaces with a date, and set out how the next pilot group is chosen.'),
    ('A customer escalates on a Friday evening that a director cannot open a contract in SPO and that their Teams channel history appears shorter than expected, and asks for an answer tonight. The contract is in an archive folder under a new parent. The channel history is complete but the default view shows 90 days. Reply tonight. Give the location and the view change in steps they can follow now, avoid technical detail, confirm nothing is lost, and say what you will verify on Monday.'),
    ('A customer escalates that two migrations have each carried a punch list into closure and that they are being asked to sign off with work outstanding: 41 app integrations and 2,000 folder renames. Reply to them. Explain what closure means and what it does not, give the owner and date for each item, propose that one of the two stays open under a named agreement, and ask which they prefer.'),
    ('A customer escalates that your team recommended keeping the source estates for 30 days and now recommends 10 with a cold export, and says the advice keeps changing. The evidence genuinely changed the recommendation. Reply to them. Explain what new evidence changed the view, show the honest part that weakens your own earlier position, restate the current recommendation once, and make clear the decision is theirs either way.'),
    ('A customer escalates that a supplier received a Teams guest invitation before their procurement notice went out, and that at the same time an external auditor was granted Shared Drive access without their approval. One was a sequencing error by your team; the other was requested in writing by their own compliance officer. Reply to them. Own the first without hedging, evidence the second without appearing to score a point, propose a single approval route for external access on both workstreams, and ask them to confirm it.')
    ) AS v(prompt)
WHERE NOT EXISTS (SELECT 1 FROM seed_state WHERE seed_key = 'l3-writing-bank-v1');

INSERT INTO seed_state (seed_key) VALUES ('l3-writing-bank-v1') ON CONFLICT DO NOTHING;
